### ISSUE TITLE
Update AddressManager with Testnet teleportation contracts

### ISSUE THREAD

**Issue by wsdt** [bobanetwork/boba_legacy#1021]
## Issue Type

@Boyuan-Chen 
https://github.com/bobanetwork/boba/pull/1015#pullrequestreview-1523912509

DM'ed you as well. 

Has no urgency, since we might update the teleportation contracts depending on the audits (but nothing serious was found - so we should be good to go for testnet). 

Thank you :-)

**Comment by boyuan-chen** [comment]
All registered!

**Comment by wsdt** [comment]
closing as done
