### ISSUE TITLE
Incorrect token address for OVM ETH in gateway

### ISSUE THREAD

**Issue by jemeza** [bobanetwork/boba_legacy#1026]
I was working on the gateway history and was noticing some issues with the previous code and with the history gateway in production.  The issue is that the gateway incorrectly labels boba token exits/deposits as ETH exits/deposits. This is because `L2_SECONDARYFEETOKEN_ADDRESS` is used in the line linked below. Instead the variable `L2_BOBA_Address`, which is the address of OVM_ETH not boba token as one might think, should be used. I'm not sure if there are other parts of the gateway that depend on this `L2_SECONDARYFEETOKEN_ADDRESS` to function correctly.

https://github.com/bobanetwork/boba/blob/f0ec957198a2afb71c6bc3feedfc84428497a0f8/packages/boba/gateway/src/services/app.service.js#L254

**Comment by sk-enya** [comment]
Closing, Absolutely it's intentional change!
