### ISSUE TITLE
Integrate Teleportation in Gateway 2.5

### ISSUE THREAD

**Issue by wsdt** [bobanetwork/boba_legacy#1034]
Teleportation contract: 
https://github.com/bobanetwork/boba/blob/develop/packages/boba/contracts/contracts/Teleportation.sol

Current deployments on testnets: 
https://github.com/bobanetwork/boba/tree/develop/packages/boba/teleportation

Deployed contracts have not yet any routes configured, what routes do we want to provide liquidity for @InoMurko (on testnet)?

Not deployed on Mainnet yet. 

---

User flow: 

1. User calls this functions via the Gateway. 
```sol
 /**
     * @dev Accepts deposits that will be disbursed to the sender's address on target L2.
     * The method reverts if the amount is less than the current
     * minDepositAmount, the amount is greater than the current
     * maxDepositAmount.
     *
     * @param _token ERC20 address of the token to deposit.
     * @param _amount The amount of token or native asset to deposit (must be the same as msg.value if native asset)
     * @param _toChainId The destination chain ID.
     */
 function teleportAsset(address _token, uint256 _amount, uint32 _toChainId)
```

Note: Only whitelisted routes are allowed, otherwise the transaction will revert. Meaning: if the destination chain & token are not both supported from the source chain, it cannot be bridged. Which assets are whitelisted has to be maintained in the frontend for now or by reading events from the contract: 

```sol
event TokenSupported(
        address indexed token,
        uint32 indexed toChainId,
        bool supported // if true, then this route is supported (from contract on source chain to destination (to) chain)
    );
```

Within a short period of time the Teleportation service on AWS should disburse the asset on the destination chain via the deployed Teleportation contract by calling: `function disburseAsset(Disbursement[] calldata _disbursements)`. 

After this event on the destination chain has been fired, you can notify the user on the gateway, that the funds have arrived: 

```sol
  event DisbursementSuccess(
        uint256 indexed depositId,
        address indexed to,
        address indexed token,
        uint256 amount,
        uint32 sourceChainId
    );
```
----

Error handling for native assets, in that case we could/should even do a retry mechanism in the gateway. 

```sol
  event DisbursementSuccess(
        uint256 indexed depositId,
        address indexed to,
        address indexed token,
        uint256 amount,
        uint32 sourceChainId
    );

    /** @dev only for native assets */
    event DisbursementFailed(
        uint256 indexed depositId,
        address indexed to,
        uint256 amount,
        uint32 sourceChainId
    );

    /** @dev Only for native assets */
    event DisbursementRetrySuccess(
        uint256 indexed depositId,
        address indexed to,
        uint256 amount,
        uint32 sourceChainId
    );
```

**Comment by sk-enya** [comment]
Thank you @wsdt !!

**Comment by wsdt** [comment]
done! @sk-enya

**Comment by InoMurko** [comment]
>Deployed contracts have not yet any routes configured, what routes do we want to provide liquidity for @InoMurko (on testnet)?

Lets start with:
Ethereum <-> Ethereum BOBA asset BOBA (both directions)
Ethereum <-> Ethereum BOBA asset ETH (both directions)

Ethereum <-> BNB asset BOBA (both directions)
BNB <-> Boba BNB asset BOBA (both directions)

Ethereum Boba<->BNB Boba asset BOBA (both directions)
Ethereum Boba<->BNB Boba asset BOBA (both directions)

Ethereum Boba<->BNB asset BOBA (both directions)
Ethereum Boba<->Ethereum asset BOBA (both directions)


I don't think there's WETH on BNB Boba. So moving ETH there wont work. Pls verify there isn't a WETH.
Make sure you're aware that for example $boba on BOBA ETH is **erc20**, but $boba on BOBA BNB is **native**.

**Comment by jemeza** [comment]
Is there a Watcher API that can be used to monitor transactions between L2s? We'll need this for this history page. Happy to work on it if necessary

**Comment by InoMurko** [comment]
Transactions in all directions emit events, so these could be indexed. But I don't think they are at the moment.

**Comment by InoMurko** [comment]
>Which assets are whitelisted has to be maintained in the frontend for now or by reading events from the contract

that seems like it will need to be indexed in a separate service or the contract would need to be modified to keep this stored?

**Comment by wsdt** [comment]
@InoMurko yes events are emitted  and can be easily read from the frontend.

**Comment by InoMurko** [comment]
events means frontend would need to "track" all events. frontends needs a middleware services that has the last information of all chains.

**Comment by wsdt** [comment]
@InoMurko  

Why would the frontend need to track all events? 

You bridge your asset, the teleporter disburses the asset in a few seconds and the Gateway knows exactly on which chain & event & address to listen to.

Edit: i see for the history page.

**Comment by wsdt** [comment]
[X] Ethereum <-> Ethereum BOBA asset BOBA (both directions)
[X] Ethereum <-> Ethereum BOBA asset ETH (both directions)

[X] Ethereum <-> BNB asset BOBA (both directions)
[X] BNB <-> Boba BNB asset BOBA (both directions)

[X] Ethereum Boba<->BNB Boba asset BOBA (both directions)

[X] Ethereum Boba<->BNB asset BOBA (both directions)

I don't think there's WETH on BNB Boba (not on testnet, but looks like BOBA Bnb mainnet has it on `0x38Ca7a190f57D38F4DC44413508e1078cD9E0045`). 

Make sure you're aware that for example $boba on BOBA ETH is erc20, but $boba on BOBA BNB is native.
--> yes even added some integration tests for that. 

---

Teleporter not deployed on BNB L1 yet --> EDIT: Done

**Comment by InoMurko** [comment]
I meant that if the frontend needs to know which routes are available, they need to know what the contract supports on a specific network - 
```
    /// @dev Assets and networks to be supported. ZeroAddress for native asset
    /// {assetAddress} => {targetChainId} => {tokenConfig}
    mapping(address => mapping(uint32 => SupportedToken)) public supportedTokens;
```

which would be this mapping that needs to be read.

perhaps @wsdt you could go through the new bridge design and create wireframes with API or contract calls that need to be created - sort of a technical integration guidance.

**Comment by InoMurko** [comment]
>I don't think there's WETH on BNB Boba (not on testnet, but looks like BOBA Bnb mainnet has it on 0x38Ca7a190f57D38F4DC44413508e1078cD9E0045).

Ask @Boyuan-Chen to deploy one (also update the docs!).

**Comment by wsdt** [comment]
@InoMurko great idea, sure thing will do!

**Comment by wsdt** [comment]
Some more documentation for integrating Teleportation: 

Mockup & SequenceDiagram: 
https://github.com/bobanetwork/boba/issues/1044

**Comment by sk-enya** [comment]
```
Estimated time => placeholder
Gas fee => 0.4440 BOBA
You will receive => 0.000 BOBA
```

1. Gas fee can be culated as 
```
const tx = await TelePortContract.populateTransaction.teleportAsset(
 token, amount, chainId)

const gasFee = await this.provider.estimateGas({...tx, from: this.gasEstimateAccount})
```

**Comment by wsdt** [comment]
@sk-enya FYI - Would replace Fast bridging logic with Teleportation as discussed based on the develop branch. 
Saw you just merged the new bridge logic/design in there.

**Comment by sk-enya** [comment]
@wsdt this means we have to complete deprecate fast bridging (LP pools)

cc @souradeep-das

**Comment by wsdt** [comment]
> @wsdt this means we have to complete deprecate fast bridging (LP pools)
> 
> cc @souradeep-das

yes, that's what I understood from Ino. 
Should be in one of the issues. 

Tagging @InoMurko for final confirmation when he is back.

**Comment by souradeep-das** [comment]
guys just to make sure the effects of deprecating fast exits are discussed- 
a) the LPs that support fast exits right now might have user funds so probably if we do remove fast exits - we should still allow users to withdraw funds through the interface
b) maybe we should give them an advanced notice, before stopping on fast exits - and hence stopping on the rewards for providing liquidity.

**Comment by wsdt** [comment]
> guys just to make sure the effects of deprecating fast exits are discussed- a) the LPs that support fast exits right now might have user funds so probably if we do remove fast exits - we should still allow users to withdraw funds through the interface b) maybe we should give them an advanced notice, before stopping on fast exits - and hence stopping on the rewards for providing liquidity.

considering this & the transition period testnet->mainnet as well, it could be a good idea to just have a 3rd tab for Teleportation. 
imho

**Comment by thenursegreg42069** [comment]
@InoMurko @wsdt what is the status of teleportation? We need some time to design front end and test once it's complete from a technical perspective. Now that Gateway 2.5 is live, we can start to consider this if it's ready to go.

**Comment by wsdt** [comment]
> @InoMurko @wsdt what is the status of teleportation? We need some time to design front end and test once it's complete from a technical perspective. Now that Gateway 2.5 is live, we can start to consider this if it's ready to go.

It's ready! Just trying to get it merged!
