### ISSUE TITLE
Deploy WETH on Boba BNB testnet

### ISSUE THREAD

**Issue by wsdt** [bobanetwork/boba_legacy#1042]
## Issue Type
Related to https://github.com/bobanetwork/boba/issues/1034#issuecomment-1643686027

```
[ ] bug report
[x] feature request
```

## Current Behavior
WETH not deployed on Boba BNB testnet, seems to be deployed on Boba BNB mainnet (`0x38Ca7a190f57D38F4DC44413508e1078cD9E0045`). 

## Suggested Fix
Deploy WETH on Boba BNB testnet (Boba BNB seems to already be deployed according to address.json, if I'm mistaken then there please as well). Including updating the documentation (happy to support here).

**Comment by boyuan-chen** [comment]
https://github.com/bobanetwork/boba/pull/1046
