### ISSUE TITLE
[TBD] Add simple WatchDog for Teleportation service

### ISSUE THREAD

**Issue by wsdt** [bobanetwork/boba_legacy#1043]
## Issue Type

```
[ ] bug report
[ x] feature request
```

## Current Behavior
When teleportation service for mainnet is deployed, we could consider a watchdog in case it's down for whatever reason or doesn't disburse an asset as expected. 

## Expected Behavior
Be notified when teleportation service is down (just as we likely have for our other core infra) or alternatively just show e.g. a small red light for the bridge service on the Gateway, that the service is in maintenance rn for example. 

@InoMurko @souradeep-das opinions?

**Comment by InoMurko** [comment]
Datadog + Tenderly + Slack and PagerDuty
