### ISSUE TITLE
Create simple wireframes for Teleportation integration based on Gateway mockups & route API/service/solution

### ISSUE THREAD

**Issue by wsdt** [bobanetwork/boba_legacy#1044]
Related to https://github.com/bobanetwork/boba/issues/1034#issuecomment-1643685241

perhaps @wsdt you could go through the new bridge design and create wireframes with API or contract calls that need to be created - sort of a technical integration guidance.

**Comment by wsdt** [comment]
user flow added here for integration: 
https://github.com/bobanetwork/boba/blob/develop/packages/boba/teleportation/README.md
@sk-enya @alvaro-ricotta

**Comment by wsdt** [comment]
![teleportation](https://github.com/bobanetwork/boba/assets/28724551/98ecd64c-6753-41c1-9ef6-6184cd1630b2)

Bridge fast (or do we have a running alternative service, I don't think so anymore right?)

**Comment by wsdt** [comment]
@thenursegreg42069 FYI

**Comment by sk-enya** [comment]
@wsdt ,
So you mean we have to replace fast bridging with `teleportAsset` or it will be separate tab besides to `classic / fast / telport` ?

**Comment by wsdt** [comment]
How does it work right now? Not sure what the advantage would be for using fast bridging - for my understanding it would be redundant to Teleportation.

@souradeep-das can you bring some light into this?

**Comment by souradeep-das** [comment]
In terms of trust assumption - Teleportation is a more centralized option than the fast bridge. So I think lets provide teleportation as a third option for now?

as for the fate of fast bridging, I think we could remove it later if it is decided to be not useful anymore. (since that would also involve the angle of deprecating LPs and user incentives)

**Comment by thenursegreg42069** [comment]
@InoMurko we discussed this last week and Fast bridge option will be removed. We will be left with Classic and "Teleportation" - please confirm.

Additionally we should take a look at "Teleportation" from a branding angle, to see if we like the name and have adequate supporting materials or if there's a better name for this feature.

**Comment by InoMurko** [comment]
> @InoMurko we discussed this last week and Fast bridge option will be removed. We will be left with Classic and "Teleportation" - please confirm.
> 
> 
> 
> Additionally we should take a look at "Teleportation" from a branding angle, to see if we like the name and have adequate supporting materials or if there's a better name for this feature.

Confirming. 


I don't think we should be branding it too much. But we should change the name perhaps.

**Comment by thenursegreg42069** [comment]
@cschlauf looping you in for name/branding of Teleport feature ^

**Comment by wsdt** [comment]
> > @InoMurko we discussed this last week and Fast bridge option will be removed. We will be left with Classic and "Teleportation" - please confirm.
> > Additionally we should take a look at "Teleportation" from a branding angle, to see if we like the name and have adequate supporting materials or if there's a better name for this feature.
> 
> Confirming.
> 
> I don't think we should be branding it too much. But we should change the name perhaps.

Kindly let me know once we have a name (if we brand it at all). If so, this might be useful: https://namelix.com/

**Comment by cschlauf** [comment]
Can you provide me a simple description of it?

**Comment by wsdt** [comment]
> Can you provide me a simple description of it?

Teleportation allows for almost instant bridging of a variety of ERC20 tokens and native assets across our L2's and several L1's. 

Context: It's quite centralized as there is a backend service issuing the assets on the destination network.
