### ISSUE TITLE
Indexing L2 <-> L2 transactions and exposing them via an API to be accessed by the frontend

### ISSUE THREAD

**Issue by jemeza** [bobanetwork/boba_legacy#1047]
## Issue Type
```
[x] feature request
```

## Current Behavior
There currently does not exist an API that can be used to get transactions that occur between L2 layers and there is no easy way for the gateway to see what routes are supported (Edit Kevin)

## Expected Behavior
Index transactions occurring between L2 layers and expose an API, perhaps similar to the watcher APIs, that can be used by the frontend to get these transactions & provide a route to show available asset routes via networks. 

---
Context: 

The frontend needs to know which routes are available, they need to know what the contract supports on a specific network -

```sol
/// @dev Assets and networks to be supported. ZeroAddress for native asset
/// {assetAddress} => {targetChainId} => {tokenConfig}
mapping(address => mapping(uint32 => SupportedToken)) public supportedTokens;
```

**Comment by wsdt** [comment]
@InoMurko is there are a preferred approach from your side? 
Otherwise I would suggest coding a minimal API that can be accessed and aggregates the events over all networks.

**Comment by InoMurko** [comment]
what is the data the frontend needs? can you show the screens @jemeza ?

**Comment by wsdt** [comment]
![image](https://github.com/bobanetwork/boba/assets/28724551/0d324c76-4b6c-4953-83d3-3cd2a974ba26)

Data can be fetched as documented here: 

Textual explanation
https://github.com/bobanetwork/boba/issues/1034

Sequence Diagram:
https://github.com/bobanetwork/boba/blob/wsdt/rm-avax-teleportation/packages/boba/teleportation/README.md

Note: The bridging is "Completed" when the DisburseAsset event has been fired for that wallet & asset on the destination chain.

**Comment by wsdt** [comment]
there seems to have been miscommunication, all data is available on the frontend directly and can be loaded that way. :-)

**Comment by wsdt** [comment]
@thenursegreg42069 FYI
