### ISSUE TITLE
Boba Rinkeby node  state-dump.lastest.json

### ISSUE THREAD

**Issue by mengyuexxx** [bobanetwork/boba_legacy#106]
I want to build Rinkeby Boba Node, can you give me the configuration of Rinkeby **state-dump.lastest.json**

**Comment by CAPtheorem** [comment]
Here is all the information you need: https://github.com/bobanetwork/boba/pull/127

Should be merged in a few hours

**Comment by CAPtheorem** [comment]
@mengyuexxx are you all set now?

**Comment by mengyuexxx** [comment]
> 

@CAPtheorem Yes, already working. Thanks
