### ISSUE TITLE
No Wallet: Dialog freezes when no wallet installed

### ISSUE THREAD

**Issue by wsdt** [bobanetwork/boba_legacy#1063]
maybe show link instead to download metamask?
## Issue Type

```
[ x] bug report
[ ] feature request
```

## Current Behavior
When no wallet installed, dialog (even the X) freezes. 

## Expected Behavior
Possibly show link to Metamask extension/website to download it. 

## Steps to Reproduce

1. Reproduced in Chrome & Edge
2. No wallet extension installed
3. Try to connect wallet

## Suggested Fix
replace with link to download metamask instead?
![image](https://github.com/bobanetwork/boba/assets/28724551/2718cfaf-c8a1-411d-a5ba-5700408661bb)

**Comment by InoMurko** [comment]
https://github.com/bobanetwork/boba/issues/688
