### ISSUE TITLE
[gateway] blockexplorer links

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#1068]
<img width="433" alt="image" src="https://github.com/bobanetwork/boba/assets/2582555/1ab0628f-0607-435f-b659-5318e9cef6a8">

Gateway links are not pointing to the right blockexplorer. Also we have multiple:
https://blockexplorer.testnet.bnb.boba.network/
https://blockexplorer.bnb.boba.network/
https://testnet.bobascan.com/
https://bobascan.com/
https://blockexplorer.testnet.avax.boba.network/
https://blockexplorer.avax.boba.network/

**Comment by jemeza** [comment]
https://github.com/bobanetwork/boba/pull/1082
