### ISSUE TITLE
[Gateway 2.5] : test release issue reports.

### ISSUE THREAD

**Issue by sk-enya** [bobanetwork/boba_legacy#1079]
## Issue Type

```
[x] bug report
[ ] feature request
```

## Current Behavior

Please list down all the issues based on testing of gateway 2.5.

### Known Issues.
- [x] Fix: Design of Stake / Dao / Earn page in Light mode.
- [x] Fix: Navbar / Header in mobile view across gateway.
- [x] Fix: Datepicker is not enable on history.

### Findings 
- [x] Start from here

**Comment by cschlauf** [comment]
When switching from Eth to BNB the prompt still advises to switch to Ethereum

If a user switches to a network - then the gateway should switch the UI for them

**Comment by cschlauf** [comment]
Need an information button describing the difference between classic and fast bridge

**Comment by cschlauf** [comment]
<img width="189" alt="Screenshot 2023-08-02 at 2 10 00 PM" src="https://github.com/bobanetwork/boba/assets/121965721/29a7e259-f0e6-40ba-901f-965ee1062a49">
This should say "token" not "amount" 


It's already fixed on Token Page

**Comment by cschlauf** [comment]
<img width="609" alt="Screenshot 2023-08-02 at 2 11 05 PM" src="https://github.com/bobanetwork/boba/assets/121965721/dcb7d5c0-e491-43c4-be10-8cfd91d2c106">
this message should come up when someone selects the bridge button 


Fix has been sent on : https://github.com/bobanetwork/boba/pull/1084

**Comment by cschlauf** [comment]
There needs to be a chain select button in the top right corner as per design below.

![Screenshot 2023-08-08 at 10 36 43 AM](https://github.com/bobanetwork/boba/assets/86316370/7a0b1edd-106a-49f9-9eee-1b2c64ac904f)

**Comment by cschlauf** [comment]
There is no BNB liquidity in the BNB fast bridge so we can not test it

**Comment by cschlauf** [comment]
Current Blocks 0/64 - double check that it's not hard coded


**PD: It's hard coded**

**Comment by cschlauf** [comment]
<img width="298" alt="Screenshot 2023-08-02 at 2 21 06 PM" src="https://github.com/bobanetwork/boba/assets/121965721/880a95d2-2dfc-494e-beb1-409042257e5c">
false positive error message regarding liquidity eth l1 to l2 


Fixes has been updated there https://github.com/bobanetwork/boba/pull/1084

**Comment by cschlauf** [comment]
<img width="365" alt="Screenshot 2023-08-02 at 2 24 46 PM" src="https://github.com/bobanetwork/boba/assets/121965721/4dc977ec-7d79-48fa-be3d-5aebdebb0609">
For testnets this should say "BNB testnet" not "BNB" make sure all of the testnet modals are correct.

**Comment by cschlauf** [comment]
3rd party bridging options disappear without explanation :

`bridges are visible only when connected to ETH mainnet!`

**Comment by cschlauf** [comment]
<img width="246" alt="Screenshot 2023-08-02 at 2 32 11 PM" src="https://github.com/bobanetwork/boba/assets/121965721/24e41037-7531-4295-ac93-8eb154fbcdf0">
1. Boba BNB not labeled appropriately 
2. Logo is missplaced.

**Comment by cschlauf** [comment]
Boba history Says the transaction was completed but it was not according to metamask
<img width="574" alt="Screenshot 2023-08-02 at 2 34 34 PM" src="https://github.com/bobanetwork/boba/assets/121965721/16d7c68a-a321-405a-bd5e-3cca93571045">

**Comment by cschlauf** [comment]
add the option to import tokens to Metamask after bridging

**Comment by cschlauf** [comment]
Modals pop up an inappropriate times and tell you to do things that are against user intent.

**Comment by cschlauf** [comment]
text needs to be updated to reflect that it's only 7 days when withdrawing from l2 to l1 <img width="182" alt="Screenshot 2023-08-02 at 2 39 31 PM" src="https://github.com/bobanetwork/boba/assets/121965721/6e5e03dc-cd39-457b-9efa-e388c4661eb4">


@cschlauf copy has been updated to 
`Although this option is always available, it takes 7 days to receive your funds when withdrawing from L2 to L1`

**Comment by cschlauf** [comment]
X Chain relay fee - seems excessive? 300 Boba to go from Boba L2 to Eth l1


From sourdeep.
  **_The cost of relaying messages L2>L1 is generally expensive in terms of gas, and since we bear that cost by running our relayers, this x chain relay fee is a way to compensate. The current fee amount of 300 boba could in some cases even be insufficient in covering the relayers cost. Although, we can technically change this fee to any amount that we want but needs to get approval from business as it determines revenue _**


That's correct please refer screenshot below and link
![Screenshot 2023-08-09 at 1 41 25 PM](https://github.com/bobanetwork/boba/assets/86316370/9f65c4c4-4ec8-4659-8ef1-b71d5f4b77cc)
https://bobascan.com/address/0x29F373e4869e69faaeCD3bF747dd1d965328b69f#readProxyContract

**Comment by cschlauf** [comment]
<img width="261" alt="Screenshot 2023-08-02 at 2 44 48 PM"
<img width="155" alt="Screenshot 2023-08-02 at 2 45 04 PM" src="https://github.com/bobanetwork/boba/assets/121965721/75a129b5-a166-4155-851e-78f234b83a4b">
 src="https://github.com/bobanetwork/boba/assets/121965721/316c9945-94ba-4032-a3d3-a66bace69545">
Discrepancy in balances. Gateway shows no balance. When metamask does have a balance.

**Comment by cschlauf** [comment]
There should be an emergency swap option.

**Comment by cschlauf** [comment]
<img width="212" alt="Screenshot 2023-08-02 at 2 49 04 PM" src="https://github.com/bobanetwork/boba/assets/121965721/94f8a0d0-6598-4cba-b179-8ffd379523fd">
make sure logos are correct

**Comment by cschlauf** [comment]
<img width="265" alt="Screenshot 2023-08-02 at 2 49 43 PM" src="https://github.com/bobanetwork/boba/assets/121965721/5c3e6aa9-b9cb-450e-94e7-0f04a5fe215e">
Need to show all network. Avax is missing

**Comment by cschlauf** [comment]
## EARN page.
<img width="148" alt="Screenshot 2023-08-02 at 2 51 47 PM" src="https://github.com/bobanetwork/boba/assets/121965721/5764e526-02dc-4cdd-b5a2-05c4cd84fa77">


1. OMG should replace with BOBA
2. Update the header on earn page 


`Both issues has been update on https://github.com/bobanetwork/boba/pull/1084`

**Comment by cschlauf** [comment]
Stake page copy needs to be updated

**Comment by cschlauf** [comment]
On earn page can't connect to Eth page. Only allows you to connect to BNB

**Comment by cschlauf** [comment]
<img width="1175" alt="Screenshot 2023-08-02 at 2 57 06 PM" src="https://github.com/bobanetwork/boba/assets/121965721/7a032db9-b5b3-4606-bd11-768f43addac8">
On light mode there is a black bar

**Comment by sk-enya** [comment]
Update copy for alert when insufficient pool info. 
`There is not enough liquidity in the fast bridge pool - reduce your amount or use the Classic Bridge`

cc @thenursegreg42069

**Comment by sk-enya** [comment]
Token picker modal should say head as `Select Tokens` instead of `Select network`.

Should render only `my tokens` as default view 

`This issue is duplicated`

Issue fixed: https://github.com/bobanetwork/boba/pull/1084

**Comment by sk-enya** [comment]
![Screenshot 2023-08-05 at 12 03 23 AM](https://github.com/bobanetwork/boba/assets/86316370/6d065ee4-0d51-4209-83ac-6ec9dcdedc7a)


In this case should have option of emergency swap.

Existing snap on wallet page.
![Screenshot 2023-08-05 at 12 05 33 AM](https://github.com/bobanetwork/boba/assets/86316370/237b64ca-f73f-4a35-845e-878257003fc0)

**Comment by sk-enya** [comment]
Add token to meta mask option in token selector modal.

**Comment by sk-enya** [comment]
## History says pending even if Tx is Success.

https://etherscan.io/tx/0x61de635513d88751493283fcbfa77691d2ae13739a9a3e4eafb40ce919997c37

**Comment by sk-enya** [comment]
> There should be an emergency swap option.

@cschlauf can you please help me with user flow for showing the emergency swap modal?

**Comment by sk-enya** [comment]
> Modals pop up an inappropriate times and tell you to do things that are against user intent.

unable to reproduce.

**Comment by sk-enya** [comment]
Consolidating issues remaining:
- [x] implementation of emergency swap https://github.com/bobanetwork/boba/pull/1097
- [ ] On earn page can't connect to Eth page. Only allows you to connect to BNB
- [x] Discrepancy in balances. Gateway shows no balance https://github.com/bobanetwork/boba/pull/1097
- [ ] Modals pop up an inappropriate times and tell you to do things that are against user intent.
- [x] There is no BNB liquidity in the BNB fast bridge so we can not test it
- [ ] When switching from Eth to BNB the prompt still advises to switch to Ethereum
- [ ] If a user switches to a network - then the gateway should switch the UI for them
- [ ] There needs to be a chain select button in the top right corner as per design below.

**Comment by cschlauf** [comment]
> 


![](https://files.slack.com/files-pri/T03QDJX5M60-F05LQRY3U31/screen_shot_2023-08-09_at_7.08.35_pm.png)
It's in wallet but should also go when a user doesn't have enough boba @thenursegreg42069 can you provide more clarity?

**Comment by cschlauf** [comment]
<img width="906" alt="Screenshot 2023-08-09 at 7 15 35 PM" src="https://github.com/bobanetwork/boba/assets/121965721/c30114be-27f8-4dc7-9953-544a61fdd1a8">

**Comment by cschlauf** [comment]
> > Modals pop up an inappropriate times and tell you to do things that are against user intent.
> 
> unable to reproduce.

we'll have to do a screen recording on the next testing session

**Comment by InoMurko** [comment]
I will create a new issue with
```
Consolidating issues remaining:
- [x] implementation of emergency swap https://github.com/bobanetwork/boba/pull/1097
- [ ] On earn page can't connect to Eth page. Only allows you to connect to BNB
- [x] Discrepancy in balances. Gateway shows no balance https://github.com/bobanetwork/boba/pull/1097
- [ ] Modals pop up an inappropriate times and tell you to do things that are against user intent.
- [x] There is no BNB liquidity in the BNB fast bridge so we can not test it
- [ ] When switching from Eth to BNB the prompt still advises to switch to Ethereum
- [ ] If a user switches to a network - then the gateway should switch the UI for them
- [ ] There needs to be a chain select button in the top right corner as per design below.
```
