### ISSUE TITLE
[Gateway 2.5] : second test release issue reports

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#1131]
Consolidating issues remaining:
- [x] implementation of emergency swap https://github.com/bobanetwork/boba/pull/1097
- [x] Discrepancy in balances. Gateway shows no balance https://github.com/bobanetwork/boba/pull/1097
- [x] There is no BNB liquidity in the BNB fast bridge so we can not test it
- [x] Modals pop up an inappropriate times and tell you to do things that are against user intent.
- [x] On earn page can't connect to Eth page. Only allows you to connect to BNB
- [x] When switching from Eth to BNB the prompt still advises to switch to Ethereum
- [ ] If a user switches to a network - then the gateway should switch the UI for them
- [x] There needs to be a chain select button in the top right corner as per design below.

**Comment by sk-enya** [comment]
- [ ] wallet connect v2 https://github.com/bobanetwork/gateway/issues/77
- [x] Wallet Dialog freezes https://github.com/bobanetwork/boba/issues/1063

**Comment by InoMurko** [comment]
awesome!

**Comment by thenursegreg42069** [comment]
Change network name from "Boba" to "Boba ETH'
![image](https://github.com/bobanetwork/boba/assets/95362638/1f3b733f-0c30-4ecd-b929-547385bde40d)

**Comment by thenursegreg42069** [comment]
Change "Add token to metamask" to "Add token to wallet"
![image](https://github.com/bobanetwork/boba/assets/95362638/a1bc3bc3-3a1f-4d5f-be68-7ecea484a4eb)

**Comment by thenursegreg42069** [comment]
Adding ETH to the wallet here adds the incorrect contract address (the others are fine).

Please double check all contract addresses on all networks. 

![image](https://github.com/bobanetwork/boba/assets/95362638/07ca779b-4670-460d-9011-8e538876b1b0)

**Comment by thenursegreg42069** [comment]
Time is wrong. Bridging from L1 to L2 does not take 7 days.

![image](https://github.com/bobanetwork/boba/assets/95362638/2a3148c9-56f6-4ca0-8c30-e7342a6d6b85)

**Comment by thenursegreg42069** [comment]
Change "Show Testnet" to "Show Testnets"
![image](https://github.com/bobanetwork/boba/assets/95362638/d337756e-eeb6-486f-b8cc-d67038fd4566)

**Comment by thenursegreg42069** [comment]
On light mode, the drop down icon under the Select token tab does not appear

![image](https://github.com/bobanetwork/boba/assets/95362638/a0aec8e9-f78a-43f3-a2f3-76416fe5a62a)

**Comment by sk-enya** [comment]
Most of this issues has been fixed and push to staging. create another issues to track freshly.
https://github.com/bobanetwork/boba/issues/1140
