### ISSUE TITLE
Change logo on github to new Boba Logo

### ISSUE THREAD

**Issue by GianBobarino** [bobanetwork/boba_legacy#1157]
## Issue Type

```
[ ] bug report
[ x] feature request
```

## Current Behavior

It's displaying the old boba network logo

## Expected Behavior

The new boba logo needs to be showing

## Steps to Reproduce

1. Change the old logo to the new

## Suggested Fix

![New Boba - Global Telegram - Profile - 512px](https://github.com/bobanetwork/boba/assets/123008441/8d3b847f-990f-4578-b8b2-b8d7742ceeab)

**Comment by InoMurko** [comment]
done
