### ISSUE TITLE
Boba balance fails when checking L2 addresses

### ISSUE THREAD

**Issue by alvaro-ricotta** [bobanetwork/boba_legacy#1158]
Currently, our dapp is checking the available balances of our users using the following list of contracts:

https://github.com/bobanetwork/boba/blob/master/packages/boba/register/addresses/addressesMainnet_0x8376ac6C3f73a25Dd994E0b0669ca7ee0C02F089.json

Up until this point, everything is fine. Yesterday, I performed some swaps on L2 to obtain the following tokens: FTM, BUSD, BNB, and MATIC, acquiring a certain amount of each of these tokens for testing purposes.

The problem arises specifically because after making the swaps, our dapp doesn't recognize the tokens that we obtained through the exchange https://oolongswap.com/. This means that it's not possible to use them within our dapp. Consequently, the token would only be functional if the user returns to the mentioned exchange, converts those tokens back into other tokens that don't have the "anyswap" label.

Given this situation, we need to find a way for users to use the tokens on our platform. This leads to several potential solutions:

One possible solution would be to add different addresses to check the corresponding balances both in the default L2 address and also the balances in the L1 address within our L2. I'm not yet sure if this issue presents itself similarly on other networks like Boba BNB or Boba Avax, but we could allocate some extra tokens on those networks to investigate the problem.

![image](https://github.com/bobanetwork/boba/assets/81116391/b0d00781-b612-4a85-88b2-5b1e08b7e56a)
![image](https://github.com/bobanetwork/boba/assets/81116391/e82600d1-455d-416a-ab4b-a4cc04a0c22a)
![image](https://github.com/bobanetwork/boba/assets/81116391/e440f34e-6c8e-4876-819a-c47dd6d495d9)

**Comment by boyuan-chen** [comment]
Our gateway only provides `earn` and `off-ramp` functions on L2. If the token is not in our list, we potentially don't have to support them.

**Comment by InoMurko** [comment]
@alvaro-ricotta is this specifically related to Earn? https://gateway.boba.network/earn

**Comment by thenursegreg42069** [comment]
@alvaro-ricotta what are the contract addresses for the assets in question

**Comment by thenursegreg42069** [comment]
Closing this issue.

These appear to be anyswap assets which someone would have bridged into Boba ETH using anyswap, not using our gateway. We will not be supporting these assets on our gateway at this time.
