### ISSUE TITLE
Block explorer links display

### ISSUE THREAD

**Issue by thenursegreg42069** [bobanetwork/boba_legacy#1175]
Currently the gateway footer includes links to Etherscan and Bobascan.

Desired behavior is to collapse these links into a single footer item called "Block Explorers" with a rollup/popout display on hover/click. This popout menu should include links to Etherscan, Bobascan, BNB Block Explorer L1, BNB Block Explorer L2, and all testnet block explorer links.

![Image](https://user-images.githubusercontent.com/95362638/265089054-4202007b-adb1-4fea-ae19-38229e895c15.png)

**Comment by sk-enya** [comment]
Hello @thenursegreg42069 ,
This links has been generated based on the network which you user connected for the moments.

**Comment by sk-enya** [comment]
As soon as you switch the network links will change also.

**Comment by sk-enya** [comment]
@yhong1073 can you please help us with design for this task?

**Comment by yhong1073** [comment]
Edited the footer with the new changes. Placed a figma comment so it is easier to locate in the file.
https://www.figma.com/file/MKj9nofAYq0GOTziHaeWRL/Boba-Gateway-2.5?type=design&node-id=108%3A1884&mode=design&t=zuOZzFG81WTuxHHg-1

**Comment by sk-enya** [comment]
- [x] update the block explorer links for Boba BNB L2.
- [x] Add block explorer for AVAX
