### ISSUE TITLE
Gateway: Loading or fallback screen design needed.

### ISSUE THREAD

**Issue by sk-enya** [bobanetwork/boba_legacy#1216]
## Issue Type

```
[ ] bug report
[x] feature request
```

## Current Behavior

As we added lazy loading modules or pages, we can observe the loading on screen with slow network.
Gateway: Loading or fallback screen design needed.

## Expected Behavior

Gateway: Loading or fallback screen design needed.

Refer screenshot below
![Screenshot 2023-09-14 at 6 54 51 PM](https://github.com/bobanetwork/boba/assets/86316370/31993443-e614-4780-82be-df9699cafef9)

**Comment by yhong1073** [comment]
Updated! This screen is the last screen on the bottom or can be found by locating the most recent figma comment.
https://www.figma.com/file/MKj9nofAYq0GOTziHaeWRL/Boba-Gateway-2.5?type=design&node-id=108%3A1884&mode=design&t=crKRydoZy0q4tzxG-1
