### ISSUE TITLE
Wrong native Asset on RouteScan for Boba BNB

### ISSUE THREAD

**Issue by wsdt** [bobanetwork/boba_legacy#1256]
## Issue Type

```
[ x] bug report
[ ] feature request
```

## Current Behavior
On Boba BNB networks the native asset is by default BOBA (except this changed and I don't know it yet). 
![image](https://github.com/bobanetwork/boba/assets/28724551/a3710080-942f-47a8-b1e5-799e51dc4d73)

## Expected Behavior
Native asset is denominated in BOBA.

## Steps to Reproduce
Replicated on Boba BNB testnet: 
https://bnb.testnet.bobascan.com/

@InoMurko FYI
not sure who to assign or tag here.

**Comment by InoMurko** [comment]
I don't understand this bug. What are you expecting to see?

**Comment by wsdt** [comment]
> I don't understand this bug. What are you expecting to see?

Alt-Boba L2's use BOBA as native asset or did we change that? 

The BlockExplorer shows BNB as native asset on L2.

**Comment by InoMurko** [comment]
On which screen do you see that?

**Comment by InoMurko** [comment]
So what you are referring to is that transaction details show fees are being paid in BNB? https://bnb.testnet.bobascan.com/tx/0x153423c7b20868068abff3f86a3121e8c17cf3f10adef483cfbba0f228b36773

**Comment by wsdt** [comment]
For example yes. 
If users pay gas in BOBA, why should the Blockexplorer show BNB instead?

Or on the account view as well: 
https://bnb.testnet.bobascan.com/address/0x5E1BE25D4A2De0083012f1B5A8030a7023fFA5bc

**Comment by InoMurko** [comment]
You're right! Thanks. Closing. Reported to Routescan.
