### ISSUE TITLE
Deploy Light bridge for OP/ARB

### ISSUE THREAD

**Issue by wsdt** [bobanetwork/boba_legacy#1287]
OP/ARB support in Gateway soon to be merged: 
https://github.com/bobanetwork/gateway/pull/101

What needs to be done? 
- Deploy teleportation contract on Optimism & Arbitrum
- Deploy teleportation services for Optimism/Arbitrum on AWS (ideally done through: https://github.com/bobanetwork/boba-aws-infrastructure/issues/84)
- Add routes on existing contracts that allow for Op/Arb routing
- Provide testnet liquidity

Routes: 

basically:

Boba BNB <> Boba ETH (both directions, BOBA only with airdrop gas on bridging user will receive some ETH on Boba ETH as Boba is not native there)
ETH (L1) <> Boba ETH (BOBA & ETH)
ETH (L1) <> Boba BNB (only BOBA as native asset)
BNB (L1) <> Boba ETH (only BOBA) -> with airdrop gas via light bridge they should get gas automatically (this way we don't need to support WETH on BNB)
BNB (L1) <> Boba BNB (only BOBA as native asset)

And for Arbitrum/Optimism: only onboarding, no offboarding (except we want to offer that as well)

OP -> Boba ETH (only ETH), no Boba support
ARB -> Boba ETH (only ETH), no Boba support
OP -> Boba BNB: not supported directly (OP -> Boba ETH [swap ETH for BOBA] -> Boba BNB), user may just use mainnet faucet or fiat on-ramps to get started directly otherwise
ARB -> Boba BNB: not supported directly (OP -> Boba ETH [swap ETH for BOBA] -> Boba BNB), user may just use mainnet faucet or fiat on-ramps to get started directly otherwise

**Comment by InoMurko** [comment]
Can you describe a bit more in detail what this issue is? Otherwise it doesn’t serve much purpose to open issues like this.
