### ISSUE TITLE
L2->L1 Ethereum is not coming in

### ISSUE THREAD

**Issue by mangcunking** [bobanetwork/boba_legacy#133]
Through the Boba Network Mainnet Bridge,
Whether the Ethereum is requested to be moved through the L2->L1 Classic Bridge
It's the 10th day.
My Ethereum doesn't come into L1
Mainnet history is still Pending

L2 hash: 0xbbe575e7f5f92f138862a7858bef6b518d02d868feb7440070a0653b72e88e08

**Comment by boyuan-chen** [comment]
Hi @mangcunking, your fund has arrived on L1. `https://etherscan.io/tx/0xb9ea27e3ad12f187a458238137dd51d61d4828ad396429d8a4e900348b912514`
