### ISSUE TITLE
Boba node sync issue

### ISSUE THREAD

**Issue by breezytm** [bobanetwork/boba_legacy#148]
My node seems to be stuck on block ``534100``. How can I resolve this issue? I thought my database was corrupted and I have already re-sync from 0 and still the issue persists. 

```
DEBUG[05-03|07:58:15.602] Ancient blocks frozen already            number=534100 hash=131c82…4ec578 frozen=444100
INFO [05-03|07:58:20.515] Syncing transaction range                start=534100 end=13759 backend=l2
INFO [05-03|07:58:20.519] Syncing transaction range                start=534100 end=13761 backend=l2
INFO [05-03|07:58:30.517] Syncing transaction range                start=534100 end=16000 backend=l2
INFO [05-03|07:58:41.012] Syncing transaction range                start=534100 end=18000 backend=l2
INFO [05-03|07:58:50.841] Syncing transaction range                start=534100 end=20000 backend=l2
INFO [05-03|07:59:00.522] Syncing transaction range                start=534100 end=22291 backend=l2
INFO [05-03|07:59:10.518] Syncing transaction range                start=534100 end=25000 backend=l2
DEBUG[05-03|07:59:15.603] Ancient blocks frozen already            number=534100 hash=131c82…4ec578 frozen=444100
INFO [05-03|07:59:20.911] Syncing transaction range                start=534100 end=27000 backend=l2
INFO [05-03|07:59:30.781] Syncing transaction range                start=534100 end=29000 backend=l2
INFO [05-03|07:59:40.909] Syncing transaction range                start=534100 end=31000 backend=l2
INFO [05-03|07:59:50.836] Syncing transaction range                start=534100 end=33000 backend=l2
INFO [05-03|08:00:00.971] Syncing transaction range                start=534100 end=35000 backend=l2
INFO [05-03|08:00:10.515] Syncing transaction range                start=534100 end=37142 backend=l2
INFO [05-03|08:00:10.518] Syncing transaction range                start=534100 end=37144 backend=l2
INFO [05-03|08:00:10.521] Syncing transaction range                start=534100 end=37145 backend=l2
INFO [05-03|08:00:10.524] Syncing transaction range                start=534100 end=37147 backend=l2
DEBUG[05-03|08:00:15.603] Ancient blocks frozen already            number=534100 hash=131c82…4ec578 frozen=444100
```

**Comment by zmyya** [comment]
I have the same problem

**Comment by breezytm** [comment]
ollowing the read me here ->  https://github.com/bobanetwork/boba/tree/develop/boba_community/boba-node

Some things have changed. you may need to delete the chaindata

**Comment by InoMurko** [comment]
hey @breezytm did you resolve your issue? can you give me more info what node you're running? are you sure it's from bobanetwork repo and not omgnetwork repo (this one got deprecated!)

**Comment by zmyya** [comment]
thanks&nbsp;This problem has been solved according to your answer



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月5日(星期四) 下午2:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bobanetwork/boba] Boba node sync issue (Issue #148)





 
ollowing the read me here -&gt;  https://github.com/bobanetwork/boba/tree/develop/boba_community/boba-node
 
Some things have changed. you may need to delete the chaindata

**Comment by zmyya** [comment]
> ollowing the read me here -> https://github.com/bobanetwork/boba/tree/develop/boba_community/boba-node
> 
> Some things have changed. you may need to delete the chaindata

thanks This problem has been solved according to your answer
