### ISSUE TITLE
USDC Doesn't Show a Value in Wallet on Gateway

### ISSUE THREAD

**Issue by Oc3anWav3** [bobanetwork/boba_legacy#158]
I bridged USDC to Boba. The USDC amount appears, but there is no value next to it. It just shows $0.00. I also have ETH and BOBA in my wallet and the amounts and values show for both of those. Everything else looks fine on the page.

**Comment by CAPtheorem** [comment]
fixed @Oc3anWav3. thank you for the bug report.
