### ISSUE TITLE
calldata compression

### ISSUE THREAD

**Issue by boyuan-chen** [bobanetwork/boba_legacy#180]
> https://github.com/Boyuan-Chen/calldata-compression/tree/main/result

We can save about **28.49%** by compressing calldata that goes into the `CTC` contract using `Zlib`.
We can save about **42.82%** by compressing calldata that goes into the `CTC` contract using `Brotli`.

The compression and gas saving results for the last 100K single transactions:
 
| Method          | Compression Ratio | Estimated Fee Savings |
| --------------- | ----------------- | ----------------- |
| Zlib            | 24.34%            | -8.15% |
| Zlib Dictionary | 22.36%            | -11.12% |
| Brotli          | 25.03%            | -5.48% |

I studied 5K events. The compression and gas saving results for the batch transaction that goes into the `CTC` contract:

| Method          | Compression Ratio | Estimated Fee Savings |
| --------------- | ----------------- | ----------------- | 
| Zlib            | 51.08%            | 29.47% | 
| Zlib Dictionary | 51.05%           | 29.44% |
| Brotli          | 59.93%           | 42.96% |

I also did the speed test for decompressing the data. Since only `data transport layer` needs to decompress the payload, I ran the speed test in `node.js`.

| Method          | Number of Batches | Time Duration |
| --------------- | ----------------- | ----------------- | 
| Brotli            | 5385           | 8.2058988s | 
| Zlib          | 5385           | 3.022597383 |

The average l2 block number in one batch is 82. The worst case and best case for decompressing data is 

| Method          | Number of Batches | Time Duration |
| --------------- | ----------------- | ----------------- | 
| Zlib (best case)           | 100           | 1.6ms | 
| Brotli (best case)         | 100          | 32.2ms |
| Zlib (worst case)           | 100           | 42.4ms | 
| Brotli (worst case)         | 100          | 166.8ms |

> The worst case means that each batch has 272 L2 blocks and the best case means that each batch only has 2 L2 blocks. I found those two cases and got the rawTransactions. I copied and pasted those data 100 times and used them as the input for the above calculation.

**Comment by boyuan-chen** [comment]
The trade off between `Zlib` and `Brotli` is significant. 

`Zlib` is 5X faster, but `Brotli` can save 15% gas fee than `Zlib`.

### Production

If we use `Brotli` for the calldata compression, the `data transport layer` for our `verifier` needs more time to decompress data. Based on our current block number and batches on L1, the `data transport layer` needs about **10 seconds** to decode 10K batches for 600K blocks and it only needs **2 seconds** to decompress data if we pick `Zlib`.

### Cost Comparison

Currently, L1 gas price is low. `Brotli` can save **1.94 ETH** for one week and `Zlib` can save **1.29 ETH**.

**Comment by mmontour1306** [comment]
A better compression ratio is more important than the relative speed difference. If necessary, we should be able to compress and decompress batches in parallel threads if it's too much work for a single CPU. However it doesn't look like that will be a problem based on that "10 seconds to decode 600K blocks" calculation.

**Comment by boyuan-chen** [comment]
> A better compression ratio is more important than the relative speed difference. If necessary, we should be able to compress and decompress batches in parallel threads if it's too much work for a single CPU. However it doesn't look like that will be a problem based on that "10 seconds to decode 600K blocks" calculation.

Only batch submitter compresses the data and DTL for the verifier decompresses it, so I tested the decompression in `node.js`.

**Comment by boyuan-chen** [comment]
I also did another tests. I picked all events that `_batchSize` is larger than 100 and got the result.
```
{
    "Zlib Compression Ratio": 0.5258261139945981,
    "Zlib Estimated Fee Savings": 0.30705299801917385,
    "Zlib Dictionary compression Ratio": 0.5257227571182014,
    "Zlib Dictionary Estimated Fee Savings": 0.30696224743713196,
    "Brotli compression Ratio": 0.6154932054079834,
    "Brotli Estimated Fee Savings": 0.44396826031572934,
    "Total Events": 1385,
    "Avg Batch Size": 139.50469314079422,
    "BatchSize > 100": true
  }
```

The `Brotli` is still significantly better than `Zlib` from the gas saving perspective.
