### ISSUE TITLE
Bug - Staking 5% Error Message

### ISSUE THREAD

**Issue by MitchellUnknown** [bobanetwork/boba_legacy#181]
Hi, MUI here...

I ran into some problems during staking on the fixed 5% page. Main problem is, after you fill out the amount you want to stake, you will get a metamask "permission" transaction. After you complete/pay this transaction, an error will occur: "Internal JSON-RPC error". The error does nothing, because the permission transaction is still approved succesfully. The annoying thing is, you have to manually fill out the amount again after the "Internal JSON-RPC error" and hit "stake" again. Now a second metamask pops-up with the completion of the staking. So the staking still works, but the UX is butchered by the error. 

As far as  I can remember, in the past you just had to fill out the **amount to stake** > hit the **stake button** > **approve permission** transaction > **approve the second transaction** > **staked!**

Now there is an error that forces the user to fill out the staked amount again. 

![1](https://user-images.githubusercontent.com/90399189/171998971-2b0bc82a-34fc-4296-9b1a-89a5b2b81253.png)

![2](https://user-images.githubusercontent.com/90399189/171998975-12a3daff-932a-41a0-90aa-14142255077a.png)

**Comment by InoMurko** [comment]
ping @sk-enya status?

**Comment by sk-enya** [comment]
Unable to reproduce this on rinkeby! @InoMurko @MitchellUnknown

**Comment by MitchellUnknown** [comment]
> Unable to reproduce this on rinkeby! @InoMurko @MitchellUnknown

Maybe it’s only on mainnet? It can be caused by DDOS? Don’t know if anybody else using mainnet has the same issue. For the record, you can still stake, I just need to fill out the stake amount twice.

**Comment by sk-enya** [comment]
invalid
