### ISSUE TITLE
[gateway] Gateway testing

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#201]
https://github.com/omgnetwork/optimism-v2/issues/35

Add a functional test (with CI - gh actions integration) for the gateway:

Perhaps use Robotframework 
https://medium.com/@joonasvenlinen/ui-regression-testing-with-robot-framework-part-1-578f2f50b721

**Comment by sk-enya** [comment]
@InoMurko  thanks for pulling up!

**Comment by sk-enya** [comment]
Closing this as we are already addressing this in #1198
