### ISSUE TITLE
URL subpages 

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#210]
on gateway: https://gateway.boba.network/
it is currently impossible to link to a subpage, like:

- https://gateway.boba.network/bridge
- https://gateway.boba.network/ecosystem
- https://gateway.boba.network/ecosystem/defi
- https://gateway.boba.network/ecosystem/nft
- https://gateway.boba.network/ecosystem/wallet
- https://gateway.boba.network/ecosystem/tool
- https://gateway.boba.network/ecosystem/token
- https://gateway.boba.network/wallet
- https://gateway.boba.network/history
- https://gateway.boba.network/earn
- https://gateway.boba.network/stake
- https://gateway.boba.network/dao

this would give us way better SEO and it's easier to navigate!

**Comment by sk-enya** [comment]
Sure, I will get it added.
