### ISSUE TITLE
Gateway for the multichain environment - task breakdown

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#211]
The idea is to have the gateway look similar to: https://gnosis-safe.io/app/welcome
Where on the top right you can switch between different chain environments.
We would gradually provide inputs on what features are disabled/enabled on which chain.
For example:
Ecosystem subpage would have less items to show on Moonbeam/Fantom/Ethereum.

**Comment by sk-enya** [comment]
@InoMurko 
Can you please help me with list of chains that we are going to support on gateway?

Along with below details for each one on both enviornment.

```
chainId
chainIdHex
name
rpcUrl
blockExplorer
transaction
```

**Comment by InoMurko** [comment]
@sk-enya you can start with Mainnet and Rinkeby (you should already have details for it).

**Comment by InoMurko** [comment]
![image](https://user-images.githubusercontent.com/2582555/196967219-c6b8d683-a64c-4aa5-b44a-2ab2eed8ac18.png)

@sk-enya chains: https://github.com/ethereum-lists/chains/pull/1700/files

**Comment by sk-enya** [comment]
@InoMurko below are the designs which @0xwinnie has prepared earlier for ref.

![Screenshot 2022-10-21 at 9 40 34 PM](https://user-images.githubusercontent.com/86316370/197241631-566e7696-0f95-4bf9-9d8a-06d32df574b8.png)
![Screenshot 2022-10-21 at 9 40 42 PM](https://user-images.githubusercontent.com/86316370/197241647-ca8d0aca-f3aa-414a-8865-1996221bdd41.png)
![Screenshot 2022-10-21 at 9 40 49 PM](https://user-images.githubusercontent.com/86316370/197241654-cdcb23e7-d082-43a8-b8e8-b222b0c17e1a.png)
![Screenshot 2022-10-21 at 9 41 00 PM](https://user-images.githubusercontent.com/86316370/197241659-83e0cdb1-69fe-441e-b28e-0fe20fb082b0.png)
![Screenshot 2022-10-21 at 9 41 06 PM](https://user-images.githubusercontent.com/86316370/197241663-b6db22c9-8715-43bb-9722-c6e947d6a2b8.png)

**Comment by InoMurko** [comment]
For bridges:

There needs to be a mapping of bridges you will develop.
L1 Avalanche can natively deposit to L2 Boba Avax
L1 Ethereum can natively deposit to L2 Boba Ethereum.
L1 Fantom can natively deposit to L2 Boba Fantom
L1 Moonbeam can natively deposit to L2 Bobabeam
etc...

there will be a separate bridge from @Boyuan Chen that will allow bridging from L2s to L2s with different risk assumptions (cc @Boyuan Chen let @Winnie Wen know you need to incorporate different risks and tradeoffs!)

Top right you would connect to different chains:
Ethereum
Ethereum Boba
Avalanche 
Avalanche Boba
Fantom 
Fantom Boba
Moonbeam
BobaBeam
etc...

**Comment by sk-enya** [comment]
@InoMurko that's what I was looking for thanks it's answers all my questions.

now only some details on which features we have to enable w.r.to.each chain.

**Comment by MitchellUnknown** [comment]
Repost from slack:

I was catching up a bit with this conversation. I think the main goal is to have "one gateway app" that will be the central hub for the users to connect their wallet to their preferred "boba multichain deployment". Instead of 5 different gateway URLs.
So create a button on the right top corner and a user can connect their wallet ...
The most important thing of being a multichain network, is that the user has everything they need in one central place. In our case the gateway.

![image](https://user-images.githubusercontent.com/90399189/197297367-8cae48c0-d803-45ad-9ef8-2ee61055caf9.png)
