### ISSUE TITLE
Gateway Boba Rinkeby Faucet does not distribute $BOBA

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#216]
## Issue Type

```
[x ] bug report
[ ] feature request
```

## Current Behavior
When one requests Rinkeby Boba and Eth on the faucet only ETH is distributed.

## Expected Behavior
Should get BOBA and ETH.

## Steps to Reproduce

1. Tweet boba bubble
2. Wait for ETH arrival
3. There’s no Boba token!

**Comment by wsdt** [comment]
Can do this. But it's not a bug, it just wasn't a requirement at that time since we had the old faucet.

**Comment by InoMurko** [comment]
Ah, okay. The text on the faucet says it distributes ETH and Boba. 

Cool, tnx!
