### ISSUE TITLE
Register chainIds

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#228]
https://github.com/ethereum-lists/chains/tree/master/_data/chains

We need to register chainIds for Moonbase and Moonbeam deployments. 
Same for Fantom and Fantom testnet(4051).

**Comment by boyuan-chen** [comment]
https://github.com/ethereum-lists/chains/pull/1324

**Comment by boyuan-chen** [comment]
Since our RPC endpoint for Bobabeam is not available, I can't add it in the above PR.
