### ISSUE TITLE
No logs for a new block

### ISSUE THREAD

**Issue by istankovic** [bobanetwork/boba_legacy#239]
## Issue Type

```
[x] bug report
[ ] feature request
```

## Current Behavior

Sometimes the RPC endpoint at https://mainnet.boba.network returns no logs for block that actually has logs.
For example, for block [716730](https://blockexplorer.boba.network/blocks/716730) we have these logs:
https://blockexplorer.boba.network/tx/0x7275eaae0d3e607b58b4407c4941a6708c14c277f229c3443d66f0705ac5cb5a/logs

however, when making a call to `get_logs`, the returned list of logs is empty.
We're using Python and `web3py` and the call to `get_logs` specifies the starting block, the end block and the address
to filter by.

## Expected Behavior

The call to `get_logs` should return all the logs.

## Steps to Reproduce

1. Poll https://mainnet.boba.network regularly (e.g. every 2s) for new blocks.
2. As soon as the new block arrives, call `get_logs`.
3. Observe the empty result, even though the block has logs. Note: a couple of tries might be needed before hitting this behaviour.

## Suggested Fix

This could be a problem with the RPC announcing the new block before the block data and logs are ready.

**Comment by boyuan-chen** [comment]
Hi @istankovic , we will improve our replica nodes' performance in our next maintenance window. We have the proxyd in front of our replica and sequencer nodes. The `eth_getLogs` is routed to the replica nodes and `eth_blockNumber` is routed to the sequencer node. The replica node takes about 1 second to sync up the up coming the block data now.

**Comment by istankovic** [comment]
> Hi @istankovic , we will improve our replica nodes' performance in our next maintenance window. We have the proxyd in front of our replica and sequencer nodes. The `eth_getLogs` is routed to the replica nodes and `eth_blockNumber` is routed to the sequencer node. The replica node takes about 1 second to sync up the up coming the block data now.

Hm, but isn't that kind of setup broken by design? In the sense that as long as the block number gets returned immediately and block data later (no matter how quickly), there will be a time where the block data will not be available for a given block number?
I am afraid that simply increasing the performance is not sufficient to fix the problem properly.

One solution would be to block all calls that need block data until the data is actually there. What do you think?

**Comment by boyuan-chen** [comment]
Hi @istankovic , we have reduced the latency. We recommend you to use `https://replica.boba.network` to query and index events. Another thing you can do is to submit transactions through `https://replica.boba.network`. Once you receive the response, you should be able to query events on `https://replica.boba.network`.

**Comment by boyuan-chen** [comment]
@istankovic BTW, the replica endpoint for Rinkeby is `https://replica.rinkeby.boba.network`. We wrote a script for you to test the events:
```
const ethers = require('ethers');

const L2_NODE_WEB3_URL = 'https://replica.rinkeby.boba.network';

const main = async() => {

  const pk = "Private Key";

  const L2Web3 = new ethers.providers.JsonRpcProvider(L2_NODE_WEB3_URL);
  const L2Wallet = new ethers.Wallet(pk).connect(L2Web3);

  const L2BOBA = new ethers.Contract(
    '0xF5B97a4860c1D81A1e915C40EcCB5E4a5E6b8309',
    new ethers.utils.Interface(['function transfer(address,uint256)']),
    L2Wallet
  )

  const tx = await L2BOBA.transfer(L2Wallet.address, ethers.utils.parseEther('0.1'))
  const receipt = await tx.wait()

  console.log(await L2Web3.getLogs(
    '0xF5B97a4860c1D81A1e915C40EcCB5E4a5E6b8309',
    receipt.blockNumber,
    receipt.blockNumber,
  ))
}

main()
```

**Comment by istankovic** [comment]
@Boyuan-Chen Thanks for the help! `https://replica.rinkeby.boba.network` seems to be working well.
