### ISSUE TITLE
[GATEWAY] Zendesk integration

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#249]
## Issue Type

```
[ ] bug report
[ X] feature request
```

## Current Behavior
At the moment, we don't have a way to get feedback from the users using the Gateway, we'd like to integrate Zendesk and see what the feedback is.

## Expected Behavior
Gateway Zendesk integration

## Steps to Reproduce
/

## Suggested Fix
We already have a development account with Zendesk cc @sk-enya reach out when you need integration details

**Comment by sk-enya** [comment]
done
