### ISSUE TITLE
[gateway] warn when merging veNFTs

### ISSUE THREAD

**Issue by souradeep-das** [bobanetwork/boba_legacy#278]
## Issue Type

```
[ ] bug report
[X] feature request (kind of)
```

## Current Behavior
if someone merges their veNFTs, token A + token B -> token B
tokenA would be burnt and they would not be able to use tokenA to vote on proposals that are on their "voting period" right now. (token B would not have the cumulative ve power because, we are checking the power at a prior timestamp)

## Expected Behavior
Someone merging their ve-locks/ veNFTs on the gateway should be informed about this

## Suggested Fix
On the gateway, If we have a merge screen on the ve locks - we should add a warning, something like "You might not be able to use the voting power of the first token, on proposals that are 'currently on their voting period'. We suggest you to vote(if any) before continuing with the merge"

**Comment by sk-enya** [comment]
Invalid now, as we don't have NFT support on gateway anymore.
