### ISSUE TITLE
sporadic test failures with new watcher

### ISSUE THREAD

**Issue by souradeep-das** [bobanetwork/boba_legacy#29]
some integ tests occasionally fails with "Provided message has already been received."

1) Basic L1<>L2 Communication
    L2 => L1
     {tag:other} should be able to perform a withdrawal from L2 -> L1:
2) Bridged tokens
    {tag:other} should withdraw tokens from L2 to the transfer recipient:

hints: fast-relayer might compete with message-relayer

**Comment by CAPtheorem** [comment]
remove duplicated message relay per @souradeep-das https://github.com/bobanetwork/boba/pull/19/commits/75a7addf80b5f0db3e4c8e435840fcf5a186be44
