### ISSUE TITLE
Supports multi-chain bridges in gateway

### ISSUE THREAD

**Issue by boyuan-chen** [bobanetwork/boba_legacy#296]
* On the Ethereum Wallet page, we need a new button next to `Fast Bridge to L2` for Boba Token.
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/46272347/184008042-c59bc09d-9efa-4ed6-93ba-97a6a5f9216b.png">
* The popup model should be
<img width="868" alt="image" src="https://user-images.githubusercontent.com/46272347/184009676-b52d01a8-8002-48a2-9a6d-1fd271a144ae.png">
* There should be another tab called `Bridge between L1s` in the history. 
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/46272347/184009733-7f5dc480-c163-4a7b-85eb-758208859c9e.png">
@trangtran-enya will provide an endpoint for you to pull data.

**Comment by Boyuan-Chen** [comment]
![image](https://user-images.githubusercontent.com/46272347/184009031-c148e593-686f-472c-ae8f-555bfbd0e7f3.png)

**Comment by Boyuan-Chen** [comment]
There should be another tab called Bridge between Alt L1s
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/46272347/184009192-2fde66d3-2c01-4293-b812-1aa83770ae46.png">

**Comment by Boyuan-Chen** [comment]
@trangtran-enya will provide an API endpoint for @sk-enya to fetch data.

**Comment by boyuan-chen** [comment]
`Brigde to L1` in history section can be renamed to `Boba Ethereum L2 to Ethereum` and `Bridge to L2` can be renamed to `Ethereum to Boba Ethereum L2` to make it clear?

**Comment by sk-enya** [comment]
@Boyuan-Chen thank you for sharing the details.
~~Instead of renaming the tab what do you think of showing this information by adding a small `i` icon or tooltip on hover?~~
Let's avoid adding tooltip instead will rename it directly so it will be easily understandable to user.

**Comment by sk-enya** [comment]
- Only enable the bridge to alt l1's for boba token as we are not supporting others.
- Option to select the L1 options out of [BNB, Avalanche, Fantom, Moonbeam]
