### ISSUE TITLE
[Suggestions] Multi-chain Gateway 

### ISSUE THREAD

**Issue by boyuan-chen** [bobanetwork/boba_legacy#303]
- Standardize the wallet name (Boba Wallet -> Bobabase Wallet)
<img width="364" alt="image" src="https://user-images.githubusercontent.com/46272347/184968030-d6614458-b6ee-4aff-8bf6-38be524cbfb5.png">
- If you press one of the below buttons and cancel the Switch Network MetaMask pop-up, the below buttons are seemingly disabled and you need to use the upper logos to switch networks.
<img width="360" alt="image" src="https://user-images.githubusercontent.com/46272347/184968343-1182e62f-e0f2-404f-a7bd-fc93d7ae7032.png">

**Comment by sk-enya** [comment]
Changes pushed!
