### ISSUE TITLE
BOBA Layer Zero Bridges Audit

### ISSUE THREAD

**Issue by boyuan-chen** [bobanetwork/boba_legacy#306]
# 1 Pragma version lock
Severity: Low
Status: Unresolved

It’s recommended to have the same compiler version that the contracts were tested with the most. This way it reduces the risk of introducing unknown bugs. There are also different versions used throughout the project, for example ^0.8.0 in LzApp.sol and ^0.8.9 in EthBridge.sol.
# 2 Unused function parameter
Severity: Informational
Status: Unresolved

In contract EthBridge.sol, at lines 126 and 127, variables _srcAddress and _nonce are not being used throughout the function.

Recommendation: Make sure the variables are not actually needed and remove them.

# 3 Variable declaration after function
Severity: Informational
Status: Unresolved

In contract LzApp.sol, at line 17 the variable failedMessages is declared after the internal function __NonblockingLzApp_init. Maintain a consistent order of variable and function declarations throughout the project.

Recommendation: Move the variable declaration to the top of the file, before any function declaration. Do this in all contract files.

# 4 Unchecked possible zero address
Severity: Medium
Status: Unresolved

In contract EthBridge.sol, at line 69 in function depositERC20To the _to function parameter can be zero and is not checked. The following function calls will not revert in case of a zero _to address, leading to undefined behavior, such as depositing tokens but not being able to receive them. 

Recommendation: Add a sanity check for the _to address to not be zero and revert otherwise.

# 5 Config param sanity check
Severity: Low
Status: Unresolved

In contract LzApp.sol, in the function setTrustedRemote, there’s no sanity check for the _srcAddress parameter. This can generate a wrong assignment even if the route can only be accessed by the owner of the contract.

Recommendation: Add a sanity check to prevent _srcAddress from being an empty slice of bytes.

# 6 Config param sanity check
Severity: Low
Status: Unresolved

In contract LzApp.sol, in the function forceResumeReceive, there’s no sanity check for the _srcAddress parameter. This can generate a wrong assignment, even if the route can only be accessed by the owner of the contract.

Recommendation: Add a sanity check to prevent _srcAddress from being an empty slice of bytes.

# 7 No upgradeability pattern used
Severity: Informational
Status: Unresolved

In contracts LzApp.sol and NonnlockingLzApp.sol you are leaving an empty reserved space, for possible future upgrades and also using the OwnableUpgradeable and Initializer contracts. However, there’s no upgradability mechanism used, such as Openzeppelin’s Upgradable Proxy.

Recommendation: If you’re not intending to use this pattern, please refactor the contracts to reflect this, otherwise complete the implementation in this direction.

**Comment by InoMurko** [comment]
This is done AFAIK.
