### ISSUE TITLE
[GATEWAY]: Fee Switcher Is visible incase Bobabase L1

### ISSUE THREAD

**Issue by sk-enya** [bobanetwork/boba_legacy#318]
## Issue Type

```
[x] bug report
[ ] feature request
```

## Current Behavior

[bobabase gateway](https://gateway.bobabase.boba.network/) showing the fee Switcher on L1.

## Expected Behavior

FeeSwitcher should not be visible in case of L1 only visible for L2.
[bobabase gateway](https://gateway.bobabase.boba.network/)

**Comment by sk-enya** [comment]
@Boyuan-Chen can you please help me with correct branch from where the changes has been deployed to 

`https://gateway.bobabase.boba.network/`

**Comment by sk-enya** [comment]
As I am unable to reproduce this issues locally with branch, `alt-l1-moonbeam`

**Comment by boyuan-chen** [comment]
I fixed this issue in `alt-l1-moonbeam`, but I haven't deployed the gateway.
