### ISSUE TITLE
Bobabase Regenesis

### ISSUE THREAD

**Issue by boyuan-chen** [bobanetwork/boba_legacy#325]
# Bobabase Regensis

## Problem
Due to update the genesis file to fix the decimal issue, the batch submitter can't submit txs to L1 and it blocks the txs from L2 to L1
```
[Kevin]
[1:23 PM]
GM, when I try to bridge from Moonbase Alpha to Bobabase on Gateway I get the following error: NS: depositETHL2 error: TypeError: e.L1StandardBridgeContract.connect(...).depositNativeToken is not a function
Also I have a Bobabase -> Moonbase Alpha bridge txn of 5,000 Boba from 9 days ago that doesn't seem to have arrived yet on MB alpha. Is there anything I need to do there? https://blockexplorer.bobabase.boba.network/tx/0x6666b2c3bb08746fa10280c2eb7562fd43967bef2b7a5e0dbee60ba7aaa2a51f
```
## Solution
We will schedule a regenesis event for Bobabase. All data will be kept and the block chain will start from block 0. This requires three hours of maintenance.

**Comment by fearyourguide2** [comment]
I'll be asking the Firefly team when is convenient for them to do the regenesis and let you know (or just follow along in Slack)

**Comment by InoMurko** [comment]
Done
