### ISSUE TITLE
[Gateway] : Design is not aligned with Figma.

### ISSUE THREAD

**Issue by sk-enya** [bobanetwork/boba_legacy#335]
## Issue Type

```
[x] bug report
[ ] feature request
```

## Current Behavior

Currently UI does not match with Figma design in general.

**Comment by InoMurko** [comment]
does @wavect-gmbh have enough understanding of this issue? Where's the Figma file? what are the discrepancies?

**Comment by wsdt** [comment]
yes we got the Figma file :-). Sahil & the main dev are in constant contact as well.

**Comment by wsdt** [comment]
Differences are quite major as for now, and we got told to only change the design and not also adapt the content if there is a mismatch.

**Comment by InoMurko** [comment]
Are we good in documenting them here? For prosperity

**Comment by wsdt** [comment]
Bridge page differences: 

### Current: 
![image](https://user-images.githubusercontent.com/28724551/218750555-2ad2cd8a-a996-4aab-bb27-14d661e97e0d.png)

---

### Mockup: 
![image](https://user-images.githubusercontent.com/28724551/218750588-85b5e24f-93aa-497b-bb2e-fb6110a8ba16.png)

![image](https://user-images.githubusercontent.com/28724551/218753536-38c8f9a8-d97a-4084-8ea4-b48ce09860a0.png)

![image](https://user-images.githubusercontent.com/28724551/218753568-d4484e0f-f199-47e8-b35b-d0fea02867d0.png)

![image](https://user-images.githubusercontent.com/28724551/218753611-dfbba415-6c08-4888-acdf-37cb1ecc29ab.png)

![image](https://user-images.githubusercontent.com/28724551/218753647-7480679b-8b18-4329-afdd-5dea7d7635ba.png)

![image](https://user-images.githubusercontent.com/28724551/218753685-0ab14539-268a-4d91-8590-628abf7b7a4c.png)

**Comment by wsdt** [comment]
FYI - Mockups / Figma file: 
https://www.figma.com/file/L0x1SJm4674X0aywP8I4gH/Boba-1.02?node-id=2706%3A29089&t=l1iyJtPlKLWao23w-0

**Comment by wsdt** [comment]
# DAO Page

### Current: 
![image](https://user-images.githubusercontent.com/28724551/218754729-301ef3c0-70cf-44c6-9350-9b93b1d2f8fd.png)


---

### Mockups: 
![image](https://user-images.githubusercontent.com/28724551/218754263-c2d08254-2470-418c-bc45-205f632b136d.png)

![image](https://user-images.githubusercontent.com/28724551/218754361-56af9038-66d6-44af-8bfb-249a14441027.png)

![image](https://user-images.githubusercontent.com/28724551/218754396-7e8586bc-e16b-4161-8a98-86595a241318.png)

![image](https://user-images.githubusercontent.com/28724551/218754449-8e1dd545-222e-4b81-a572-fa1a7fed86cd.png)

![image](https://user-images.githubusercontent.com/28724551/218754532-2bee1ddd-35fa-458f-b2af-b6eaa338873a.png)

**Comment by wsdt** [comment]
# Wallet

### Current: 
![image](https://user-images.githubusercontent.com/28724551/218756373-54f479cf-cce6-48c0-859f-8e2dfa833c6e.png)

#### Boba wallet:
![image](https://user-images.githubusercontent.com/28724551/218756473-55764964-cf4f-4d51-adbe-762ccdae614b.png)


---

### Mockups: 
![image](https://user-images.githubusercontent.com/28724551/218756299-c741e526-946f-495d-8f14-a7f27b1665c4.png)

![image](https://user-images.githubusercontent.com/28724551/218756925-a17dc08d-5bc2-4739-bbd8-d2b10b444559.png)

![image](https://user-images.githubusercontent.com/28724551/218756968-21466701-6ae2-4eb2-a152-32020455a9fb.png)

![image](https://user-images.githubusercontent.com/28724551/218757025-bcd85736-1b15-450b-87c3-b8b2af033fcd.png)



#### Boba wallet: 
![image](https://user-images.githubusercontent.com/28724551/218756614-d17daee1-38d4-4382-95b8-f0321686abcc.png)

![image](https://user-images.githubusercontent.com/28724551/218756675-279115d7-49d6-4eb6-bf2e-a659d645e588.png)

![image](https://user-images.githubusercontent.com/28724551/218756730-407eb4fd-d06c-48c6-bbd7-2826ca7829bc.png)

![image](https://user-images.githubusercontent.com/28724551/218756799-27da47f5-0b8a-470f-bb0c-fdc1fa692c8d.png)

![image](https://user-images.githubusercontent.com/28724551/218756874-8acc12dd-c0a1-430d-b8b4-5013e26ce826.png)

![image](https://user-images.githubusercontent.com/28724551/218757101-87ac463b-8a84-4abb-ad74-d5e43c06ed09.png)

**Comment by wsdt** [comment]
# Earn

## Current
![image](https://user-images.githubusercontent.com/28724551/218757812-56774abf-4bb5-4a8d-8a3e-669de34f15da.png)


---

## Mockups
![image](https://user-images.githubusercontent.com/28724551/218758031-27354f92-c3ab-4c45-b919-18994aa3725f.png)

![image](https://user-images.githubusercontent.com/28724551/218758090-719b99a5-94b5-44cb-a158-d294fa0976cb.png)

![image](https://user-images.githubusercontent.com/28724551/218758126-779b49b6-bbb7-46df-a6a0-f9f6b5fa086e.png)

![image](https://user-images.githubusercontent.com/28724551/218758189-7706f5d6-798f-4fde-b629-62936840ffd1.png)

![image](https://user-images.githubusercontent.com/28724551/218758239-3d5a4b72-61c1-42b1-aa8d-36403ad0d535.png)

**Comment by wsdt** [comment]
---

These screens are just to have a comparison of both states, please refer to the Figma mentioned above to have a closer look at component styles, etc.

**Comment by sk-enya** [comment]
> Differences are quite major as for now, and we got told to only change the design and not also adapt the content if there is a mismatch.

Thank you @wsdt for adding screens.
@InoMurko we just want to avoid the regression and get the design applied to gateway.

**Comment by wsdt** [comment]
major work should be done, will continue with smaller issues from now on
