### ISSUE TITLE
[Gateway] Sentry for bobanetwork ORG

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#343]
## Issue Type

```
[x] bug report
[ ] feature request
```

## Current Behavior
Use bobanetwork enya's sentry account

## Expected Behavior
Move away from OMG sentry account. Double check slack integration

- [x] Create new project on Enya's Lab Sentry Account
- [x] Update the keys of sentry for rinkeby.
- [ ] Enable the sentry for other gateway L2 gateway
- [x] Sentry Error should have gateway specific identifier's like tags or Env. make use of `REACT_APP_CHAIN`

## Suggested Fix
Swap api keys

**Comment by sk-enya** [comment]
@InoMurko slack integration with new sentry is done, need to update the gateway with new sentry project configuration.

**Comment by InoMurko** [comment]
Awesome. Please also assign @Boyuan-Chen to complete this and close later. Thanks

**Comment by sk-enya** [comment]
@Boyuan-Chen can you please update the gateway with new sentry configuration. please let me know if needed anything from me.

**Comment by sk-enya** [comment]
Already done!
