### ISSUE TITLE
API WATCHER IS FAILING WITH 404

### ISSUE THREAD

**Issue by sk-enya** [bobanetwork/boba_legacy#357]
## Issue Type

```
[x] bug report
[ ] feature request
```

## Current Behavior
`https://api-watcher.mainnet.boba.network/`. this seems to be down below calls are failing continously on gateway.
get.l1.airdrop , get.l2.airdrop

## Expected Behavior
Above call should work.

## Steps to Reproduce

1. Open gateway and check logs in console
2.
3.

**Comment by sk-enya** [comment]
@InoMurko

**Comment by sk-enya** [comment]
![Screenshot 2022-09-16 at 8 04 00 PM](https://user-images.githubusercontent.com/86316370/190664076-d16fd2d2-b23d-4ec1-b51c-45c858ea281d.png)

**Comment by boyuan-chen** [comment]
I can't reproduce this error on https://gateway.boba.network

**Comment by sk-enya** [comment]
Hmm it's issues of key. closing
