### ISSUE TITLE
[Gateway]: VeBoba&Vote new pools information should has to be populated in const file.

### ISSUE THREAD

**Issue by sk-enya** [bobanetwork/boba_legacy#370]
## Issue Type

```
[x] bug report
[ ] feature request
```

## Current Behavior

Update the pools details hardcoded for `rinkeby` here once deployment done on `mainnet`.
[`packages/boba/gateway/src/util/poolDetails.js`](https://github.com/bobanetwork/boba/pull/292/files#diff-b0a34ab6ad1afcd1b872a05bcef4b2565749ee25b9c0cbdbcd08000f08dc1182R1)

## Expected Behavior

Update the pools details hardcoded for `rinkeby` here once deployment done on `mainnet`.
[`packages/boba/gateway/src/util/poolDetails.js`](https://github.com/bobanetwork/boba/pull/292/files#diff-b0a34ab6ad1afcd1b872a05bcef4b2565749ee25b9c0cbdbcd08000f08dc1182R1)

**Comment by sk-enya** [comment]
constant changes are available in PR
https://github.com/bobanetwork/boba/pull/292

**Comment by sk-enya** [comment]
Remove tokonomics from gateway so closing the issues.

**Comment by souradeep-das** [comment]
sounds good!
