### ISSUE TITLE
[nft bridge] EVO nft bridge registration on Boba Avax

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#374]
const EVO_NFT_L1 = "0x454a0E479ac78e508a95880216C06F50bf3C321C";
const EVO_NFT_L2 = "0x3e9694a37846C864C67253af6F5d1F534ff3BF46";

**Comment by boyuan-chen** [comment]
Registered

**Comment by InoMurko** [comment]
thank you!
