### ISSUE TITLE
[gateway] expose depositing to other account

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#393]
## Issue Type

```
[ ] bug report
[ x] feature request
```

## Current Behavior
We're not exposing two methods of native bridging:
```
depositEthTo(account)
depositERC20To(account)
```

## Expected Behavior
```
// Deposit ETH to another l2 wallet
const depositToTx = await Proxy__L1StandardBridge.depositETHTo(
  TargetAddress, // l2 target address
  depositAmount,
  1300000, // l2 gas limit
  ethers.utils.formatBytes32String(new Date().getTime().toString()), // byte data
  {value: ETHAmount}
)
```

## Steps to Reproduce

1.
2.
3.

## Suggested Fix
Expose bridging to XYZ account on L2.

Also fix the UX (native bridge at the top, other bridges to the bottom)

**Comment by InoMurko** [comment]
@sk-enya ... @souradeep-das will help you if you have problems implementing

**Comment by InoMurko** [comment]
@0xwinnie should fix the UX (Boba Classic Bridge needs to be on top), Third party bridges bellow, and new inputs for this issue.

**Comment by sk-enya** [comment]
![Screenshot 2022-10-04 at 11 07 15 AM](https://user-images.githubusercontent.com/86316370/193742628-aff3ffff-298c-48c3-872c-f9d34a9d7005.png)
