### ISSUE TITLE
[gateway] instances cannot be reached from different parts of the world

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#395]
Does not work from Europe (@InoMurko ) /Asia (@sk-enya ):
https://bobabeam.boba.network/
https://bobabase.boba.network/
https://testnet.avax.boba.network/
https://avax.boba.network/
https://testnet.bnb.boba.network/
https://bnb.boba.network/
Works:
https://gateway.rinkeby.boba.network/
https://gateway.boba.network/

**Comment by boyuan-chen** [comment]
Does https://gateway.bobabeam.boba.network work for you?

**Comment by boyuan-chen** [comment]
The bobabeam gateway should be reachable globally based on the tests. 
https://www.uptimia.com/website-availability-test/f3b53342

**Comment by InoMurko** [comment]
> The bobabeam gateway should be reachable globally based on the tests. 
> 
> https://www.uptimia.com/website-availability-test/f3b53342

I can't reach our alts with my phone either (LTE). 😩

**Comment by sk-enya** [comment]
<img width="698" alt="Screenshot 2022-10-01 at 4 02 32 PM" src="https://user-images.githubusercontent.com/86316370/193405314-a1cfefd3-f5ac-4d64-9bf0-06420aaa7b7b.png">
Getting something like this when I open other gateway which @InoMurko has mention not working.

**Comment by sk-enya** [comment]
> Does https://gateway.bobabeam.boba.network/ work for you? 
@Boyuan-Chen 
Yeah this is working for me.

**Comment by InoMurko** [comment]
```
curl https://bobabase.boba.network/ --verbose
*   Trying 34.195.233.67:443...
* Connected to bobabase.boba.network (34.195.233.67) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=bobabeam.boba.network
*  start date: May  4 00:00:00 2022 GMT
*  expire date: Jun  2 23:59:59 2023 GMT
*  subjectAltName: host "bobabase.boba.network" matched cert's "bobabase.boba.network"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x139010000)
> GET / HTTP/2
> Host: bobabase.boba.network
> user-agent: curl/7.79.1
> accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 405
< date: Sat, 01 Oct 2022 10:50:37 GMT
< content-length: 0
< vary: Origin
<
* Connection #0 to host bobabase.boba.network left intact
```

**Comment by InoMurko** [comment]
> > Does https://gateway.bobabeam.boba.network/ work for you? 
> 
> @Boyuan-Chen 
> 
> Yeah this is working for me.

For me too
