### ISSUE TITLE
[gateway]: multi wallet support like wallet connect and others

### ISSUE THREAD

**Issue by boyuan-chen** [bobanetwork/boba_legacy#397]
## Issue Type

```
[ ] bug report
[x] feature request
```

## Expected Behavior

Support the Wallet Connect to let users use the multisig

## Steps to Reproduce

1.
2.
3.

**Comment by sk-enya** [comment]
RainbowKit to have multi-wallet support and other benefits even going to support custodial wallets & fiat on ramps

https://www.rainbowkit.com/

Fairly easy to integrate & widely used.

**Comment by boyuan-chen** [comment]
> RainbowKit to have multi-wallet support and other benefits even going to support custodial wallets & fiat on ramps
> 
> https://www.rainbowkit.com/
> 
> Fairly easy to integrate & widely used.

Ok! Sounds good!

**Comment by boyuan-chen** [comment]
rainbowkit and web3connect are not suitable at this moment. They use the wagmi package as the wrapper like the ethers package. However, wagmi uses react hook to create interfaces which is not suitable for our networkservice.

Therefor, the walletconnect v1 is added.

**Comment by boyuan-chen** [comment]
https://github.com/bobanetwork/boba/pull/625
