### ISSUE TITLE
[Gateway] How to handle the special case of ERC20 tokens in gateway?

### ISSUE THREAD

**Issue by boyuan-chen** [bobanetwork/boba_legacy#404]
## Issue Type

```
[ ] bug report
[x] feature request
```

## Current Behavior

https://github.com/bobanetwork/boba/pull/403

We should have a standard way to handle the special tokens that are not ERC20 compatible in our gateway.

## Steps to Reproduce

1.
2.
3.

**Comment by sk-enya** [comment]
@Boyuan-Chen can you please help how do we have to handle the special tokens. can you please add any example tokens and it's way of handling?

**Comment by sk-enya** [comment]
looks already completed!
