### ISSUE TITLE
Boba SDK

### ISSUE THREAD

**Issue by wsdt** [bobanetwork/boba_legacy#43]
ToDo: 
- Plug & Play deployment of AWS endpoint, e.g.:

```
sam deploy \
  --template-file turing.yml \
  --stack-name priceFeed \
  --capabilities CAPABILITY_IAM
```

---

- NPM package for common use cases (KYC, Turing Examples Price Feed, etc.) --> all of them should have a ready to deploy template file for AWS.

--- 

- DevOps / VCS / Tests pipeline, etc. whatever is needed for safe usage.

**Comment by CAPtheorem** [comment]
AWS example here: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-getting-started-hello-world.html
