### ISSUE TITLE
[gateway] alt-l1 - faucet amounts are wrong

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#433]
![image](https://user-images.githubusercontent.com/2582555/197530197-bcef7b25-337f-4a5c-9393-859e7dcafe32.png)

We're saying we're giving 10 testnet BOBA, but we're giving 0.1!

**Comment by wsdt** [comment]
Which chain?

**Comment by InoMurko** [comment]
BNB, but I think all have this issue :-)

**Comment by wsdt** [comment]
ok will check! thx

**Comment by wsdt** [comment]
@InoMurko Interesting, can't find the `10 testnet BOBA` text in neither the BobaBase nor the Boba main repository. 

That's the actual text everywhere: 

```jsx
<Typography variant="body3" sx={{ opacity: 0.65, marginBottom: "10px" }}>
              Welcome developers.
              For testnet BOBA and ETH, tweet your Boba Bubble and
              then paste the tweet link in the field below.
            </Typography>
```

Feels like this was a spontaneous change by someone? 

On the Eth chain it's correct as well: 
https://gateway.rinkeby.boba.network/wallet

**Comment by InoMurko** [comment]
Have you tried alt-l1?

**Comment by InoMurko** [comment]
```
<Typography variant="body3" sx={{ opacity: 0.65, marginBottom: "10px" }}>
              Welcome developers.
              For 10 testnet BOBA, tweet your Boba Bubble and
              then paste the tweet link in the field below.
            </Typography>
```

~/boba/packages/boba/gateway/src/containers/wallet/token/Token.js

**Comment by wsdt** [comment]
@sk-enya why the change?

Returned to previous welcome message. 
https://github.com/bobanetwork/boba/commit/d5a9139a0210a4b6184d00da3b693010225d871c

**Comment by boyuan-chen** [comment]
Can we update the faucet amount in the contract?

**Comment by wsdt** [comment]
Done: 
https://blockexplorer.testnet.bnb.boba.network/tx/0xe35bb75e8d83cc79716843c8e106030bd272cd7d5c06ad83289238e8a9846f29

Set native currency claim amount to 5 + token claim amount to 5 as requested. 

Want me to do it for all Alt-L2's? If so please confirm that this ratio is correct / desired. 

@Boyuan-Chen

**Comment by wsdt** [comment]
got confirmation from Ino.

**Comment by wsdt** [comment]
Fuji: 
https://blockexplorer.testnet.avax.boba.network/tx/0x55d51018399fec835d52160a3ae86aea4a55eb7df25cebb3d37c674af434edc0

Opera Testnet: 
https://blockexplorer.testnet.bobaopera.boba.network/tx/0x0110b2abde7c3cfd6a0ce37115ea410fb34737cf544e0e7f429d8dcf7a618830

**Comment by wsdt** [comment]
waiting for BobaBeam confirmation

**Comment by InoMurko** [comment]
> waiting for BobaBeam confirmation

From who? Or what exactly?

**Comment by boyuan-chen** [comment]
> > waiting for BobaBeam confirmation
> 
> From who? Or what exactly?

The bobabeam is confirmed
