### ISSUE TITLE
[Teleportation] Gateway supports the new bridge

### ISSUE THREAD

**Issue by boyuan-chen** [bobanetwork/boba_legacy#450]
## Issue Type

```
[ ] bug report
[x] feature request
```

## Expected Behavior

The goal is to add a new button called `bridge to Alt L2s` for BOBA token and a modal for bridging, just like the L1 cross chain bridge

## Steps to Reproduce

1.
2.
3.

**Comment by sk-enya** [comment]
Teleportation support has been already added on the gateway for the Testnet environment.

Closing as we duplicated issue for https://github.com/bobanetwork/gateway/issues/78
