### ISSUE TITLE
[hybrid compute] deploy https://turing.rinkeby.boba.network/

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#457]
## Issue Type
We need a copy of https://turing.rinkeby.boba.network/ deployed to https://hcb.goerli.boba.network/
```
[ ] bug report
[x ] feature request
```

## Current Behavior
Turing and rinkeby, both deprecated

## Expected Behavior
Use Hybrid Compute Boba.
Decomission Rinkeby, provision Goerli.

## Steps to Reproduce

1.
2.
3.

**Comment by wsdt** [comment]
It's here:
https://github.com/bobanetwork/boba/tree/develop/boba_community/turing-start

**Comment by InoMurko** [comment]
I'll fix the code if @Boyuan-Chen deploys :P

**Comment by wsdt** [comment]
Fix? Is something broken? or you mean just redeploying?

**Comment by InoMurko** [comment]
turing should be swapped for hybrid compute (hc) and references to Rinkeby removed, if they exist.

**Comment by wsdt** [comment]
ah sure - happy to do that (not having access to DNS though - needs to be done by one of you guys then).

**Comment by wsdt** [comment]
Closing as PR merged & waiting for release cycle
