### ISSUE TITLE
[Gateway] : Features needs to be enable for each deployment on gateway

### ISSUE THREAD

**Issue by sk-enya** [bobanetwork/boba_legacy#459]
## Issue Type

```
[ ] bug report
[ x ] feature request
```

## Current Behavior
Currently we have all the features on gateway enable for the mainnet and rinkeby.

## Expected Behavior
Need help on what features needs to be enable for the each deployment like.

1. MoonBeam <> BobaBeam
2. MoonBase <> Bobabase
3. Avalanche <> Boba Avax
4. Fantom <> Boba Fantom

**Comment by sk-enya** [comment]
@Boyuan-Chen @InoMurko can you please list down the features which we have to enable for the each deployment so I will setup the gateway accordingly.

**Comment by sk-enya** [comment]
![Screenshot 2022-11-23 at 10 15 36 PM](https://user-images.githubusercontent.com/86316370/203602228-2fa9fcbe-1974-4592-b397-f918dcac8fec.png)

**Comment by boyuan-chen** [comment]
<img width="277" alt="image" src="https://user-images.githubusercontent.com/46272347/203606517-5f38f658-de4c-40fc-a0c3-20c34e650152.png">

**Comment by InoMurko** [comment]
@Sahil Kashetwar 
Ethereum Boba: 
Bridge
Ecosystem
Wallet
History
Earn
Stake
BOBA Chains
Dao

BNB Boba:
Bridge
Ecosystem
Wallet
History
BOBA Chains

Moonbeam boba:

Bridge
Ecosystem
Wallet
History
BOBA Chains

Fantom boba:

Bridge
Ecosystem
Wallet
History
BOBA Chains
Avax Boba:

Bridge
Ecosystem
Wallet
History
BOBA Chains

**Comment by sk-enya** [comment]
Footer pages will be as is.
FAQs 
BobaScope 
Blockexplorer  (link will be different for each deployments)
Boba Docs

**Comment by sk-enya** [comment]
@InoMurko we have `monster` in the menu list as well do we have to show it for all deployments? or only in case Ethereum?
