### ISSUE TITLE
Gateway Bridge screen first impressions

### ISSUE THREAD

**Issue by CAPtheorem** [bobanetwork/boba_legacy#46]
1/ Key button is labeled transfer - this should be called Fast Bridge, MultiBridge or Classic Bridge?
2/ The Bridge switcher does nothing? When I click ’switch’ nothing seems to happen
3/ Unclear which bridge I’m about to use - could change the Botton label to say ‘classic bridge’ or ‘fast bridge’ to reduce confusion - see #1
4/ Prices/fees/labels do not change with bridge type setting - for example, when I go to the classic bridge, there should be no 0.1% fee etc. The percent fees are only relevant to the fast bridge
5/ “To classic bridge” button, resulting popup message is misleading - for example, when you are on Boba L2, there is no such thing as the multibridge. So the bridge switcher wording needs to depend on the layer you are on
6/ The amount +/- buttons don’t seem to do anything?
6/ Fast bridge, the percent fee (that depends on the amount you want to fast exit) is fixed == 0 in the present version?
7/ When on L1, how does the person toggle from the multi bridge to the normal bridges? Could not select multiple tokens. Suggest if(layer1) then show multi bridge yes/no picker. If multibridge, enable multiple token selection in the token picker (as many as 4 tokens can be bridged at once IF L1 == true and MULTIBRIDGE == true)

**Comment by sk-enya** [comment]
4/ Prices/fees/labels do not change with bridge type setting - for example, when I go to the classic bridge, there should be no 0.1% fee etc. The percent fees are only relevant to the fast bridge
currently this is just hard coded, can you please help me with correct behaviour here.

**Comment by sk-enya** [comment]
6/ The amount +/- buttons don’t seem to do anything?
_**Amount + / - buttons will only enable in case of fast bridge with multi tokens.**_

**Comment by sk-enya** [comment]
**Note** : _There is no connection of any kind between the fast bridge and the multibridge_

there should be separate option above the token input to switch to the multi bridge.
when user selects multi bridge then :

- We should say `select tokens` instead of `select token` 
- We should show the + / - action buttons
-  We do not show `Recommendations : classic bridge --- To fast bridge`
