### ISSUE TITLE
[Gateway] Should enable the button after confirming the tx from L1 to L2

### ISSUE THREAD

**Issue by boyuan-chen** [bobanetwork/boba_legacy#478]
## Issue Type

```
[ ] bug report
[x] feature request
```

## Current Behavior

![image](https://user-images.githubusercontent.com/46272347/203663978-427b2e35-6bb9-4586-b311-3694775fc82f.png)

## Expected Behavior

The button should be re-enabled when users deposit funds from L1 to L2.
## Steps to Reproduce

1.
2.
3.

**Comment by sk-enya** [comment]
No more valid requirement, as wallet page has been removed!
