### ISSUE TITLE
[Gateway] Add NOW Wallet

### ISSUE THREAD

**Issue by OyunaNW** [bobanetwork/boba_legacy#500]
## Issue Type

```
[ ] bug report
[x] feature request
```

## Current Behavior

Add NOW Wallet in Boba Ecosystem among other wallets

## Expected Behavior

NOW Wallet is presented here https://boba.network/ecosystem/ with a clickable link and socials

## Steps to Reproduce

1. Add NOW Wallet logo with a clickable link: https://walletnow.app/ (png logo attached)
2. Add a description "NOW Wallet is a fast, secure and non-custodial crypto wallet developed by the team of ChangeNOW Crypto Exchange service"
3. Add Social Media - Twitter: https://twitter.com/NOW_Wallet Telegram: https://t.me/NOWWallet_channel
![now wallet logo](https://user-images.githubusercontent.com/121167586/208896016-4116c68e-f584-40a7-baf3-8c6b3337cfd4.png)

**Comment by sk-enya** [comment]
This is already added will be available on gateway in upcomming release.
