### ISSUE TITLE
[ AA ] bundler needs to be added to docker-compose-side.yml

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#504]
## Issue Type

```
[ ] bug report
[ ] feature request
```

## Expected Behavior
account abstraction is put into a docker container - boba_deployer_aa  with the bundler contracts! (purge them from bundler) - if it’s too tied/coupled - lets recheck our assumptions
account abstraction also deploys samples, entrypoint contract is registered on address manager
bundler fetches the entrypoint contract from address manager

**Comment by souradeep-das** [comment]
closed by #531 and #508

**Comment by InoMurko** [comment]
thank you for cleaning up @souradeep-das
