### ISSUE TITLE
[Gateway] : clickjacking Security measures 

### ISSUE THREAD

**Issue by sk-enya** [bobanetwork/boba_legacy#528]
## Issue Type

```
- [x] bug report
- [ ] feature request
```

## Current Behavior

Validate the gateway against the Clickjacking Attacks and other security measures. 

## Expected Behavior

Implement preventing measures like .
 1. prevent the website from loading into iframe or on different domain by setting `x-frame-options` value to `sameorigin` or `deny`
 2. Setup correct `Content Security Policy` to avoid loading on another domain.

## Steps to Reproduce

1. Embed the `gateway.boba.network` it should not load so can avoid the user from accessing it.
3.
4.

## Suggested Fix

1. Setup automated test to validate Clickjacking vulnerabilities.

**Comment by boyuan-chen** [comment]
Fixed
