### ISSUE TITLE
Whenever the native RPC is down with some reason gateway STOP listing tokens.

### ISSUE THREAD

**Issue by sk-enya** [bobanetwork/boba_legacy#532]
## Issue Type

```
[x] bug report
[ ] feature request
```

## Current Behavior
Whenever the RPC is down with some reason gateway stops listing tokens as `fetchBalances` won't work..

While testing the BNB and Fantom I came across this and it started working once I change the rpc in network config on gateway.

## Expected Behavior

It should switch between available rpc if there is alternative option or rpc url.

## Steps to Reproduce

1.
2.
3.

**Comment by sk-enya** [comment]
@Boyuan-Chen would love to know your thoughts, is this already considered?

We can see the list of alternate rpc at 
https://chainlist.org/chain/97

**Comment by boyuan-chen** [comment]
The RPC points of BNB and FTM sometimes are not stable. It would be great if the gateway can switch the endpoint. Don't worry about Avalanche and Ethereum.

**Comment by sk-enya** [comment]
Okay, sure will look into the implementation of switching between endpoints if one is failing.

**Comment by sk-enya** [comment]
closing as it's done
