### ISSUE TITLE
[Gateway BNB] Setting new fee 0.5 BNB left in wallet

### ISSUE THREAD

**Issue by MitchellUnknown** [bobanetwork/boba_legacy#536]
Hi, 

On the BNB deployment when a user want to switch their network fee setting from boba > BNB they will get a message that their wallet needs to contain at least 0.5BNB, thats more than 100$. I think it's a typo, or at least needs to be corrected to 0.05 or 0.025 BNB. 

![image](https://user-images.githubusercontent.com/90399189/214310546-fefb861f-99c9-4613-b09b-d5ef7cd7e888.png)

**Comment by sk-enya** [comment]
@MitchellUnknown can you please help me with the minimum balance required for other deployments, like AVAX, Moonbeam, and Fantom?

Currently we have are checking to have min `1 BOBA` and `0.5 OTHER native Tokens`

**Comment by MitchellUnknown** [comment]
I don't have funds on Fantom or BobaBeam you guys should put funds on it and try for yourself. I know that Avax and BNB have the same 0.5 OTHER native token warning. I think ether has something like 0.0025 or 0.025?

**Comment by sk-enya** [comment]
Yeah sure.  In the case of ETH user should have a min of 0.002 ETH to use as a fee token.

**Comment by boyuan-chen** [comment]
Fixed
