### ISSUE TITLE
[ Gateway ] : Issues observed 2.0

### ISSUE THREAD

**Issue by sk-enya** [bobanetwork/boba_legacy#546]
## Issue Type

```
[x] bug report
[ ] feature request
```

## Current Behavior

List of issues observed on the current gateway.

- [x] - Auto-switching of MM network not working. It always failed with the **wrong network modal**. we can put this in a better way like  ***You are on the incorrect network. Please click to switch to Ethereum Network*** so the user won't get confused.
- [ ] - Api watcher on goerli failing with 502. 
- [x] - On completion of transactions L1 -> L2 or L2 -> L1 gateway should have a modal with the link to explorer using tx hash so the user can navigate to BobaScan or EtherScan easily without navigating to the history page.
- [x] - Use of the boba fee only works for L2 so we should show the fee switching option in case of layer 2 only.
- [x] - Stake modal design is not aligned with other models on the gateway. 

- History Page:

  1. Fix the transactions list design and make it more aligned with other gateway design fonts are not readable.
  2. In case the `bridge between l1's` tx hash link is broken, navigating the user back to the gateway back, better to remove the link if it's not a valid link or fix the link with LayerzeroScan.
  
  
- Mobile View Notes:

- [x] 1. Gas Fee is not visible in mobile view, which can be seen at the footer on the desktop.
- [x]   2. Fee Switcher Tool tip is not visible
- [x]   4. Menu listing style is broken
- [x]   5. Menu is not closing on clicking menu item
- [x]   6. Alignment of the theme icon is not correct in the case of the menu
- [x]   7. History page tabs styling doesn't looks good on mobile, need designer thoughts.
- [x]   8. Dao Page Style on Mobile needs to fix, need designer thoughts.

**Comment by InoMurko** [comment]
How is this breakind down going?

**Comment by sk-enya** [comment]
Added corresponding tasks to [project](https://github.com/orgs/bobanetwork/projects/10/views/1)

**Comment by sk-enya** [comment]
Closing as completed
