### ISSUE TITLE
Prepare MM Service for gateway.

### ISSUE THREAD

**Issue by sk-enya** [bobanetwork/boba_legacy#550]
## Issue Type

```
[ ] bug report
[x] feature request
```

## Current Behavior

Prepare MetaMask Service for gateway as currently everything has been added to the networkService.

## Expected Behavior

Service name as `metamask.service.js` or `wallet.service.js` with features or functions listed below.

1. ConnectTo Metamask.
2. Disconnect
3. Switch Chain
4. Add Network Layer L1 or L2

## Steps to Reproduce

1.
6.
7.

**Comment by InoMurko** [comment]
Is this refactoring? Can we add more details (@sk-enya) so that @wavect-gmbh can pick this up?

**Comment by wsdt** [comment]
sure, would be great to have more details and we can start working.

**Comment by sk-enya** [comment]
@InoMurko yeah it's a refactoring of network service.

@wsdt here we just want to extract MetaMask-related functions from `networkService.js` and move them to a separate file. as like `connect to mm`, `switch chain`, `disconnect`, `addNewChain`. please do let me know if you need any more details from me.

**Comment by boyuan-chen** [comment]
Please review: https://github.com/bobanetwork/boba/pull/620/files
