### ISSUE TITLE
[gateway] introduce gateway version in the footer of the page

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#551]
## Issue Type

```
[ ] bug report
[x] feature request
```

## Current Behavior
We don't exactly know which version of the gateway we're looking at.

## Expected Behavior
Show version of the project `"version": "0.0.3",` and make sure it gets bumped in releases.

## Steps to Reproduce

1.
2.
3.

## Suggested Fix
Show gateway version in the footer

**Comment by sk-enya** [comment]
Somehow Gateway version info got removed on refactoring footer, please add it back

**Comment by sk-enya** [comment]
closing as already completed!
