### ISSUE TITLE
 i can't find the 119 usdc bridger from boba to bsc? 

### ISSUE THREAD

**Issue by jpbuss** [bobanetwork/boba_legacy#564]
## Issue Type

```
[ x] bug report
[ ] feature request
```

## Steps to Reproduce

1.
2.
3.

**Comment by jpbuss** [comment]
hey i can't find the 119 usdc bridger from boba to bsc? https://blockexplorer.bnb.boba.network/tx/0xec947929897d3bdb388a333d07ca77108177829e4e9bf16d286104d8f5d5e923 with
https://gateway.bnb.boba.network/wallet

**Comment by boyuan-chen** [comment]
Hi! Here is the tx for your 119 USDC. https://bscscan.com/tx/0xd70511dd71020cdd0a92b84e6a1058c9c15d614ea3a1f27ef77c3251ffab3bbb
