### ISSUE TITLE
[AA] aa-sdk side issues for Boba

### ISSUE THREAD

**Issue by souradeep-das** [bobanetwork/boba_legacy#576]
### Low-level provider (to be used on scripts/tests)

- #### 1. wallet deployer factory cannot be used with sdk (to deploy wallets automatically with initCode if wallet does not exist)
reason: 
    `createUnsignedUserOp()` on the sdk failes only for boba:
    Fails getting sender address from initCode at - `getCounterFactualAddress`
    This is because `getSenderAddress()` method on EntryPoint returns the calcualted address(from intiCode)
    as a reverted error to not deploy the initCode, but get and return only the resultant address

    The sdk reads this resultant address from the errorArgs, which is of the form:
    [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="getSenderAddress(bytes)",
    data="0x6ca7b8060000000000000000000000009179e5563d0fa43edde674281c8f6f76b956a3ce",
    errorArgs=["0x9179e5563d0FA43EDDE674281c8f6f76B956a3CE"], errorName="SenderAddressResult",
    errorSignature="SenderAddressResult(address)", reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)

    On Boba however, the revert data is not returned, resulting in
     (missing revert data in call exception; Transaction reverted without a reason string)
    and the sdk is unable to calculate sender

- #### 2. deterministic deployer on sdk uses arachnid proxy, should use a new factory
https://github.com/bobanetwork/boba/blob/develop/packages/boba/bundler/packages/sdk/src/DeterministicDeployer.ts

### High-level provider (to be used by gateway/UI)

- #### 3. using a remote signer with eth_sendTransaction is not supported on Boba(which the sdk uses), transactions would need to be sent from an `ethers.wallet`
used throughout https://github.com/bobanetwork/boba/blob/develop/packages/boba/bundler/packages/sdk/src/DeterministicDeployer.ts

- #### 4. assoicated with above - confirm wrapProvider works
wrapProvider would use counterfactual address which is associated with low-level provider issue 1

- [x] add integ tests for High-level provider

**Comment by InoMurko** [comment]
this is done per project, but it doesn't close the ticket! yuck!

**Comment by InoMurko** [comment]
is there anything else here @souradeep-das ?

**Comment by souradeep-das** [comment]
no this is done! 😄
