### ISSUE TITLE
Fix link on Gateway for Boba ETH Testnet

### ISSUE THREAD

**Issue by GianBobarino** [bobanetwork/boba_legacy#591]
## Issue Type

```
[x] bug report
[] feature request
```

## Current Behavior

Current link is https://gateway.rinkeby.boba.network/
<img width="1285" alt="Screen Shot 2023-02-12 at 12 43 22 PM" src="https://user-images.githubusercontent.com/123008441/218336059-8ca93254-6f6b-4b04-8630-c2b181a365a9.png">

## Expected Behavior

Change to https://gateway.goerli.boba.network/

## Steps to Reproduce

1.
2.
3.

**Comment by sk-enya** [comment]
@InoMurko seems like code is already there on develop branch for this 
https://github.com/bobanetwork/boba/blob/develop/packages/boba/gateway/src/containers/ecosystem/project.list.js#L693

can you please help me, which version of the build is on the production gateway? so will raise the PR against the same.

**Comment by InoMurko** [comment]
@GianBobarino pls confirm this is now fixed: https://gateway.boba.network/bobachains/testnet

Reopen if the issue persist, thanks.
