### ISSUE TITLE
Need Design : History Page [Desktop / Mobile]

### ISSUE THREAD

**Issue by sk-enya** [bobanetwork/boba_legacy#604]
Please refer to the existing history page below.

**Before Connect:**
<img width="1126" alt="Screenshot 2023-02-27 at 6 42 49 PM" src="https://user-images.githubusercontent.com/86316370/221572943-4bd1932a-cec3-4b38-8cb3-1c9b40da896e.png">

**After Connect**
![scrnli_27_02_2023_18-41-50](https://user-images.githubusercontent.com/86316370/221573033-ec9dbf41-502e-41b2-aa3f-5bce6a459680.png)

**L1 -> L2**:
<img width="1047" alt="Screenshot 2023-02-27 at 6 46 15 PM" src="https://user-images.githubusercontent.com/86316370/221573544-0c94bf30-2005-4902-b09f-35968bb41818.png">

**Pending:**
<img width="1059" alt="Screenshot 2023-02-27 at 6 46 23 PM" src="https://user-images.githubusercontent.com/86316370/221573580-943f3d9c-0d6a-4f6e-803b-9eaee9b4e9cb.png">

**Comment by sk-enya** [comment]
@julienaziza please find the answer to questions.

**1/ What are the most important information, needed to be shown on closed card/single row in table? (default state)**
We should show the block, hash with a clickable link, time, tx value, and title.

**2/ What are the most important information, needed to be shown on open card/expanded row in table? (clicked on “More information”)**
Please refer to the 3rd screenshot for the information that we have shown.

**3/ Is there any links to other websites/products that need to be included?**
Yeah,the tx hash link will redirect the user to block explore. [like](https://testnet.bscscan.com/tx/0x6b022c1ec01743f85d95560e5657da8611f05de6350f1aed99f171333eafbc8f)

**4/ Is there any additional text we need to display? Is this text fixed or will be live text, changed by code?**
Yeah, only tab's names will be going to change based on the selected networks like _Avax / Bnb / Moonbeam / Fantom_  there is no other changing text everything will be hard coded like labels for input and date picker.

**Comment by sk-enya** [comment]
Just notice transaction history section design on figma which is no complete, you can refer to prepare the history page design.
<img width="800" alt="Screenshot 2023-02-27 at 10 39 03 PM" src="https://user-images.githubusercontent.com/86316370/221632970-8e1063f3-e2f5-4832-aefa-ee9ec788651f.png">

**Comment by wsdt** [comment]
@yhong1073 will overtake this now as discussed with @julienaziza and Ino already :-)

**Comment by wsdt** [comment]
FYI: 
https://www.figma.com/file/7J6ERQh0jw0IGfOaxfENsl/Gateway-Boba_History-Page?node-id=0%3A1&t=2G0l9koa8Fec9xcy-1

**Comment by InoMurko** [comment]
@Boyuan-Chen didn't we remove the history page as being unnecessery? or am I mistaking?

Is this only for deposits and withdrawals?

**Comment by InoMurko** [comment]
seems like it’s bridge transactions only so that makes sense

**Comment by sk-enya** [comment]
Already handled so closing!
