### ISSUE TITLE
How long should Fast Bridge to L1 take?

### ISSUE THREAD

**Issue by JettaRed** [bobanetwork/boba_legacy#61]
I initiated a Fast Bridge to L1 approximately 18 hours ago.  The history shows Success for each hash.  It was a large amount of BOBA and I know there has been low liquidity recently, but I want to make sure something is not stuck.  My wallet is on a Ledger Nano X connected through MetaMask.

I know a couple of months ago, bridging transactions were failing with using a Ledger wallet and wonder if that is still a problem.

Thanks! 

![image](https://user-images.githubusercontent.com/36326584/161342624-5fc07bea-f121-4a9e-b8b4-166d4585a387.png)

**Comment by CAPtheorem** [comment]
Your TX was initiated `18 hours ago | March-31-2022 09:56:46 PM +-7 UTC` and the bridge was completed `17 hrs 8 mins ago (Apr-01-2022 05:29:48 AM +UTC)` according to Etherscan. This means that the bridge took approximately 33 minutes. https://etherscan.io/tx/0xd23253e35ba3f5bc94adef9eeb1f6ff21acd93aa221ec612a98636ab09ff8b52

**Comment by JettaRed** [comment]
Thanks!
