### ISSUE TITLE
[ Gateway ] : Refactor earn page from classical to functional

### ISSUE THREAD

**Issue by sk-enya** [bobanetwork/boba_legacy#615]
## Issue Type

```
[ x ] bug report
[ ] feature request
```

## Current Behavior

Even after setting up a connection with meta mask, `connect button with user prompt` takes time to disappear.

## Expected Behavior

Connect button should disappear as soon as the connection with the metamask is set up

## Steps to Reproduce

1.
2.
3.

## Suggested Fix

Refactoring the Earn page component with functions and hooks will solve the rendering issue.

**Comment by boyuan-chen** [comment]
https://github.com/bobanetwork/boba/pull/631
