### ISSUE TITLE
[Gateway] FeeSwitcher Button clickable zone is smaller then the button area

### ISSUE THREAD

**Issue by this-dave** [bobanetwork/boba_legacy#622]
## Issue Type
```
[x] bug report
[ ] feature request
```

## Current Behavior

Click on the "BOBA/ETH" (FeeSwitcher) button doesn't work on the complete button

![image](https://user-images.githubusercontent.com/49922326/222759871-55c0e5ab-548a-4ab4-b305-23a527f64522.png)

## Expected Behavior
When clicking on the FeeSwitcher Button ("Boba" for example) it should work on the whole button.

## Steps to Reproduce

1. Connect to the Boba gateway https://gateway.boba.network/
2. Now there should be a button with "ETH" or "BOBA" next to "fee"
3. Click on the arrow icon in this button -> doesn't work

## Suggested Fix

Click has to be reworked so that it works on the whole button not only the text

**Comment by wsdt** [comment]
done, @this-dave could you link the PR here or has it yet to be pushed?

**Comment by this-dave** [comment]
> done, @this-dave could you link the PR here or has it yet to be pushed?

PR is now created #635
