### ISSUE TITLE
[TBD] [Gateway] Change "connected" information on wallet page (currently: feat/one-gateway)

### ISSUE THREAD

**Issue by this-dave** [bobanetwork/boba_legacy#623]
## Issue Type

```
[ ] bug report
[ ] feature request
[x] change request
```

## Current Behavior

On the "Wallet page" there is currently the information "connected" or "disconnected", depending on whether you are connected to your wallet.

![image](https://user-images.githubusercontent.com/49922326/222761649-6f6ce011-74a4-4e73-9c2c-43bc4d70b725.png)
![image](https://user-images.githubusercontent.com/49922326/222761585-fc6d9e18-f2e6-40f3-b561-c2b61abf84cb.png)

## Suggested Fix

Remove the two pieces of information, as they basically offer no added value for the user and do not appear anywhere else on the website or in the design. In the case of "disconnected", it even looks a bit off in the design as the info is wether needed nor does it align to the other design. It would be even more useful to display the info "connected" or "disconnected" globally in the header, for example, in case the user needs this help or this info should be displayed on the website.

**Comment by sk-enya** [comment]
yeah, As it's not on a website other than the wallet page and has no added value to the user so better to remove it.

**connect** button or layer switcher buttons on top right corner convey this information very well by making it active and off so don't think we need to add some extra text or indicators but open for thoughts.

<img width="138" alt="Screenshot 2023-03-03 at 9 39 52 PM" src="https://user-images.githubusercontent.com/86316370/222770219-942c76b0-de72-4736-a0b6-415425c972d0.png">

<img width="172" alt="Screenshot 2023-03-03 at 9 39 29 PM" src="https://user-images.githubusercontent.com/86316370/222770204-3edc9b33-7e31-4a07-b69d-08dd1363a6af.png">
