### ISSUE TITLE
[Gateway]: Update logo to new design

### ISSUE THREAD

**Issue by sk-enya** [bobanetwork/boba_legacy#628]
## Issue Type

```
[ x ] bug report
[ ] feature request
```

## Current Behavior

Current logo is older one let's get the new colored logo design for dark and light mode and update on gateway.

Need to update logo
<img width="107" alt="Screenshot 2023-03-06 at 6 02 57 PM" src="https://user-images.githubusercontent.com/86316370/223111511-ac42a1fb-fa08-4710-94ce-3b9a3b82db77.png">

## Expected Behavior

Use the logo design below on gateway so we can have same logo across all boba websites.
<img width="826" alt="Screenshot 2023-03-06 at 6 02 50 PM" src="https://user-images.githubusercontent.com/86316370/223111711-f1818831-9f9f-4c6e-b00b-5e7dc386f7da.png">

## Steps to Reproduce

1.
2.
3.

**Comment by sk-enya** [comment]
@julienaziza can you please share the svg file for latest logo once!

**Comment by julienaziza** [comment]
![boba2 logo-color](https://user-images.githubusercontent.com/126458420/223112753-195a59dc-b359-4024-ada7-25d627b48f6d.svg)
![boba2 logo](https://user-images.githubusercontent.com/126458420/223112774-22e66a9f-237e-48df-a72a-ccd29dc3fe2d.svg)

Hi everyone. Apologies if this seems a bit confusing. I'm also discovering this with you now. So the original boba logo has always been the one with the "a" in 2 separate pieces. I believe the Figma file that you're using as reference was done before my time (don't know by who) so quite a long time ago. I'm not sure why the "boba" logo is slightly different in that Figma file. By principle, we should just have the exact same logo across everything. However, adding variations to it like the "2" is ok. Therefore, I've recreated the Boba2 logo just now for you guys, in black and color.

**Comment by wsdt** [comment]
white: 
![223112774-22e66a9f-237e-48df-a72a-ccd29dc3fe2d](https://user-images.githubusercontent.com/28724551/224284041-1cb8b286-3932-43ca-a690-4d7846852b9a.svg)

**Comment by wsdt** [comment]
@julienaziza do we have a company file share where we uploaded these (to have them for future projects somewhere)

**Comment by wsdt** [comment]
fixed in #653
