### ISSUE TITLE
Self-delegated xBOBA not being counted correctly

### ISSUE THREAD

**Issue by CAPtheorem** [bobanetwork/boba_legacy#63]
**Potential bug** People with zero BOBA but xBOBA: 

(1) self delegate - which seems to work correctly - but then 
(2) when they vote, only their zero BOBA is counted, but their self-delegated xBOBA is not counted.

**Expected behavior** - their vote total is the sum of BOBA and xBOBa.

Based on a first read, the contracts look good, and this is definitely something that was checked in the integrations tests. So something more subtle.  

Minor - also noticed that the two key DAO contracts are not verified, which should definitely be done.

**Comment by souradeep-das** [comment]
since voting power is based on the historical checkpoint for the specific proposal, this is potentially people - who delegated after the proposal's voting start time and hence do not have voting power at the proposal's startBlock time

all three dao contracts are now verified
