### ISSUE TITLE
[Gateway] Rework .scss files to styled components

### ISSUE THREAD

**Issue by this-dave** [bobanetwork/boba_legacy#633]
## Issue Type

```
[ ] bug report
[ ] feature request
[x] change request
```

## Current Behavior
While redesigning the Gateway pages I sometimes came across .scss files. Since the project works mainly with styled components, this is often very inconvenient because, for example, you can't use variables from the theme in the scss file and some things are not as easy as working with styled components. It would also improve readability and consistency of the whole codebase.

There would also be a problem with the lightmode/darkmode switcher, because some colors should be changed with theme variables and because you can't use them in the .scss files, this would be the only solution to change the colors, but the @media dark setting only works with the browser settings, so it won't work with our "theme switcher"

For example: For the tooltip component we need different title colors for darkmode and lightmode, in this case there is only one .scss file. I added a "@media (prefers-color-scheme: dark)" for reference, but that would only have an effect if the browser setting is the same as the theme switcher. So if you use the browser setting "darkmode" but the theme is set to "lightmode", a wrong color will be displayed.

```
.title {
  font-size: 14px;
  padding: 13px 16px 12px;
  border-radius: 12px;
  color: rgba(3, 19, 19, 0.85);
}

@media (prefers-color-scheme: dark) {
  .title {
    font-size: 14px;
    padding: 13px 16px 12px;
    border-radius: 12px;
    color: rgba(255, 255, 255, 0.85);
  }
}
```

## Suggested Fix
Rework certain .scss files to styled components

**Comment by wsdt** [comment]
got the go.

**Comment by sk-enya** [comment]
refer to files that need to be converted to styled-components.



![Image](https://user-images.githubusercontent.com/86316370/225778074-9855e87a-3668-4ee4-8073-f3020cbd7b71.png)

**Comment by sk-enya** [comment]
Closing as changes has been already cleanup and fix!
