### ISSUE TITLE
Not a bug, but it is unclear that we have multichain instances.

### ISSUE THREAD

**Issue by cschlauf** [bobanetwork/boba_legacy#636]

**Comment by cschlauf** [comment]
All destinations should appear here and it should default to which network you are on. 

![Image](https://user-images.githubusercontent.com/121965721/223802561-0b71310f-3370-4619-b8aa-9570c493849a.png)

**Comment by sk-enya** [comment]
@cschlauf yeah this is good idea will add those.

Just have question for default network for gateway.
 _As we are supporting only Goerli, BNB, AVAX, Fantom, Moonbeam on gateway but let's say user is on sepolia or optimism so how do we have to handle those cases? _

**Comment by cschlauf** [comment]
If it's not a supported gateway then I would say have a drop down or pop up module to allow them to choose from our selection.

**Comment by sk-enya** [comment]
Yup

**Comment by sk-enya** [comment]
### **Firstly we need to enable the bridge for other deployments to have this dropdown**

**Comment by sk-enya** [comment]
has been addressed already in 2.5 release.
