### ISSUE TITLE
FAQ's at the bottom left hand corner go to random FAQ's. Best to just send to devdocs

### ISSUE THREAD

**Issue by cschlauf** [bobanetwork/boba_legacy#638]

**Comment by cschlauf** [comment]
https://gateway-test.tooling.boba.network/help

**Comment by sk-enya** [comment]
@cschlauf you mean these questions are not valid anymore?


![Image](https://user-images.githubusercontent.com/86316370/224130922-96d36d66-5fb5-4bfd-b087-0c5d089f2fdf.png)

If **FAQ** is of no use so does it make sense to remove? 
As we already have boba docs link in bottom left corner.

**Comment by sk-enya** [comment]
@cschlauf any thoughts if we redirect the user to docs link below?

[https://docs.boba.network/faq](https://docs.boba.network/faq)

**Comment by cschlauf** [comment]
yes send them to that link instead. Thanks
