### ISSUE TITLE
What is boba scope? Also in bottom left hand corner

### ISSUE THREAD

**Issue by cschlauf** [bobanetwork/boba_legacy#639]

**Comment by cschlauf** [comment]
https://gateway-test.tooling.boba.network/bobascope

**Comment by sk-enya** [comment]
@Boyuan-Chen can you please share more details what is the use boba scope it seems it's just history page but not sure what is the actual use of this page.

**Comment by boyuan-chen** [comment]
It shows the pending exit transactions. I will take some time to debug this.
