### ISSUE TITLE
node is stuck at block 239336

### ISSUE THREAD

**Issue by suyog-bhat** [bobanetwork/boba_legacy#64]
DEBUG[04-04|05:38:37.735] VM returned with error                   err="insufficient balance for transfer"    ret=0x
DEBUG[04-04|05:38:37.736] Transaction failed, account skipped      hash=2a57dd…bd0205 err="insufficient balance for transfer"
ERROR[04-04|05:38:37.736] Problem committing transaction           msg="Cannot commit transaction in miner"
ERROR[04-04|05:38:37.736] Got error waiting for transaction to be added to chain msg="Cannot commit transaction in miner"
ERROR[04-04|05:38:37.736] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: Cannot commit transaction in miner"

**Comment by ducknessman** [comment]
> DEBUG[04-04|05:38:37.735] VM returned with error err="insufficient balance for transfer" ret=0x
DEBUG[04-04|05:38:37.736] Transaction failed, account skipped hash=2a57dd…bd0205 err="insufficient balance for transfer"
ERROR[04-04|05:38:37.736] Problem committing transaction msg="Cannot commit transaction in miner"
ERROR[04-04|05:38:37.736] Got error waiting for transaction to be added to chain msg="Cannot commit transaction in miner"
ERROR[04-04|05:38:37.736] Could not verify error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: Cannot commit transaction in miner"

how to solve this problem?
