### ISSUE TITLE
Dev Tools are not clear

### ISSUE THREAD

**Issue by cschlauf** [bobanetwork/boba_legacy#640]

**Comment by cschlauf** [comment]
Dev tools should at least have a link documenting what it is

**Comment by sk-enya** [comment]
@Boyuan-Chen can you please share more details about dev tools would be great if you can help me there is any documentation or share requirement details..

**Comment by boyuan-chen** [comment]
Dev Tool is for developers. The usage of the TX builder is to interact with your smart contract without writing the code. Developers can add the smart contract address and interface in our gateway and use functions from the interface to read or write.

**Comment by boyuan-chen** [comment]
It's how Gnosis says about the TX builder. It's really intuitive for developers.
![image](https://user-images.githubusercontent.com/46272347/224133548-c445340d-f3b1-4251-b0ad-ea6e01d8da1a.png)

**Comment by sk-enya** [comment]
@cschlauf please do let us know if we have to add more details and content on the dev tools page or we are good to close this issue?

**Comment by cschlauf** [comment]
Follow Boyuan's lead here.

**Comment by thenursegreg42069** [comment]
1) Keep the "Dev Tools" footer item but change the linked URL to https://docs.boba.network/for-developers
2) Create a new article on https://docs.boba.network/for-developers called "Transaction Builder"
3) Under this new article, include the link to https://gateway.boba.network/devtools along with any documentation on this tool that currently exists.
