### ISSUE TITLE
ON the BNB bridge. When connecting to dev tools it directs you to connect to Boba but does not do anything

### ISSUE THREAD

**Issue by cschlauf** [bobanetwork/boba_legacy#641]

**Comment by cschlauf** [comment]
![Image](https://user-images.githubusercontent.com/121965721/223804907-2d5f6536-6fc4-4b1b-9af3-65dd4878f410.png)

**Comment by sk-enya** [comment]
@cschlauf can you please help me which network you are trying this?

BNB, Goerli or other?

**Comment by cschlauf** [comment]
Disregard - I had to refresh. But if we eliminate steps to switch networks this should solve the issue.
