### ISSUE TITLE
Automatic connections

### ISSUE THREAD

**Issue by cschlauf** [bobanetwork/boba_legacy#642]

**Comment by cschlauf** [comment]
Anytime the bridge asks a user to connect to a specified blockchain it should do it automatically. If the RPC info for this network is not already added to their wallet it should prompt them to add it - then it should auto fill that info.

**Comment by cschlauf** [comment]
If people don't want to add auto. Just link them to the list of RPC's on our docs or to chainlist.

**Comment by sk-enya** [comment]
we are supporting auto-fill of adding the network to metamask!
Closing the issue!
