### ISSUE TITLE
Gateway: UI Redesign As current design is flat and uninspiring.

### ISSUE THREAD

**Issue by cschlauf** [bobanetwork/boba_legacy#646]
https://www.loom.com/share/60ddd25a07474498929ae1682c6e9e24

**Comment by cschlauf** [comment]
Understand design is still not finished but we need to have a modern gateway akin to Arbitrum and Optimism. Current design is flat and uninspiring. Juilien can easily mock something like the below examples up. Go for clean and clinical.

**Comment by cschlauf** [comment]
![Image](https://user-images.githubusercontent.com/121965721/223810534-8a87fe69-98c8-4efb-a64b-e913805fc17f.png)

**Comment by cschlauf** [comment]
![Image](https://user-images.githubusercontent.com/121965721/223811096-58fe7047-4916-42a2-874e-8ae3253e73e6.png)

**Comment by cschlauf** [comment]
![Image](https://user-images.githubusercontent.com/121965721/223811751-ef5616d5-4fef-4a9f-bab6-590f171a468f.png)

**Comment by wsdt** [comment]
possibly involve @yhong1073

**Comment by yhong1073** [comment]
I don't know if Juilien is supposed to design for this, but I did create a design for the bridge page when the wallet is disconnected because the feedback seemed to focus on that specific page. 
Please let me know if I am missing something or need to design something additionally.
 https://www.figma.com/file/7J6ERQh0jw0IGfOaxfENsl/Gateway-Boba?node-id=34%3A337&t=DCGXNaMhnr6xw5xT-1

**Comment by sk-enya** [comment]
@yhong1073 design is awesome! it would be good if you can add design for next flow on selection of network or token like it's confusing for developer whether we have to open select dropdown or modal popup with search feature.



![Image](https://user-images.githubusercontent.com/86316370/224437970-bb99a672-47f5-43ec-bba6-7233eb5a1ec5.png)

**Comment by sk-enya** [comment]
How the buttons `Connect Wallet` differ in both screens solid and outlined one.

**Comment by yhong1073** [comment]
> How the buttons `Connect Wallet` differ in both screens solid and outlined one.

For that, it is just different button designs. One is more colorful and not part of the design system and the other is the button part of the design system.

**Comment by yhong1073** [comment]
Updated with token and chain selection
https://www.figma.com/file/7J6ERQh0jw0IGfOaxfENsl/Gateway-Boba?node-id=34%3A337&t=hpsTaQZ55MEfbQZf-1

**Comment by wsdt** [comment]
@sk-enya do we already want to work on this? or this TBD?
And if yes, what parts of it should already be implemented? @InoMurko

**Comment by sk-enya** [comment]
Closing as design has been already defined and implemented.
