### ISSUE TITLE
[Gateway] Design Feedback from Yoonhee

### ISSUE THREAD

**Issue by sk-enya** [bobanetwork/boba_legacy#648]
[boba_gateway_ edits.pdf](https://github.com/bobanetwork/boba/files/10928802/boba_gateway_.edits.pdf)

**Comment by wsdt** [comment]
@this-dave let's do that one.

**Comment by this-dave** [comment]
@sk-enya Are these changes all correct? Or should I leave some out, e.g. the "bridge" page because of the other issues being discussed?

**Comment by sk-enya** [comment]
@this-dave aah, okay, 
I did some changes on bridge page which is here in PR. https://github.com/bobanetwork/boba/pull/655

So please look into other changes except header as it needs to be center as far as I know we have all pages centered aligned so don't change header position other are good to do.

Please do let me know if you need any other details from me.

**Comment by this-dave** [comment]
Design changes were implemented in #662 - ready for merge
