### ISSUE TITLE
[AA] add integ tests for alt-l1

### ISSUE THREAD

**Issue by souradeep-das** [bobanetwork/boba_legacy#670]
Add tests for alt-l1-
i) general aa_wallet
ii) gpoPaymaster that is intended to work with alt-l1 deployments

**Comment by wsdt** [comment]
@souradeep-das are you on this? Because it is 'in progress'?

**Comment by souradeep-das** [comment]
yes! i'm on this. https://github.com/bobanetwork/boba/pull/687
will revive now the bundler is merged
