### ISSUE TITLE
For people that are trying Boba and bridging for the first time, they will have no Boba on L2.   They will be very frustrated and stuck when they want to bridge back  seeing this message "Insufficient BOBA balance to cover xChain message relay. You need at least 10.0 BOBA."

### ISSUE THREAD

**Issue by cryptoxman** [bobanetwork/boba_legacy#673]

**Comment by sk-enya** [comment]
@cryptoxman, when the user is trying boba and bridging for first time what should be the behavour if they don't have boba.
Does it make sens to provide the option to buy boba on Banxa or emergency swap is which we already have on the wallet page?

**Comment by sk-enya** [comment]
Now we have option to do the emergency swap and also 3rd party bridges so we can close the issue.



![Image](https://github.com/bobanetwork/boba/assets/86316370/378f51fe-cabf-42e4-9513-5e73ac208c1e)
![Image](https://github.com/bobanetwork/boba/assets/86316370/79b94fa0-f348-4908-9fa8-0048ee1dcae0)
