### ISSUE TITLE
[AA] fix - src/runOp.ts

### ISSUE THREAD

**Issue by souradeep-das** [bobanetwork/boba_legacy#677]

**Comment by InoMurko** [comment]
@souradeep-das what was this about?

**Comment by souradeep-das** [comment]
ohh this is about the failure of the account-abstraction/src/runop.ts script. Its an issue with upstream too and is broken. It's not something that we use currently though

to be run with:
yarn run runop

**Comment by wsdt** [comment]
question: is that something we want contribute to or should we just wait for upstream to fix and pull?
