### ISSUE TITLE
Remove Boba Chains on Gateway 2.0 [One Gateway]

### ISSUE THREAD

**Issue by sk-enya** [bobanetwork/boba_legacy#694]
## Issue Type

```
[ x ] bug report
[ ] feature request
```

## Current Behavior

Currently we have boba chains page on gateway 
`https://gateway.boba.network/bobachains/mainnet` which should list of block explorer and gateway we have for different network like BNB, FANTOM etc. 

## Expected Behavior

As in case of one gateway ([Gateway2.0](https://gateway-test.tooling.boba.network/)) we have option to switch between network so we should also remove the gateway links from ecosystem page?

Even we don't even need to show the cards for block explorer as user can see the block explorer url specific to network at the footer.

## Steps to Reproduce

1.
2.
3.

**Comment by sk-enya** [comment]
@InoMurko & @Boyuan-Chen can you please share your thoughts?

**Comment by boyuan-chen** [comment]
Sounds good to me. Can we add a chain name as a parameter to url, like https://gateway.boba.network?network=mainnet?

**Comment by sk-enya** [comment]
do you mean the chain name network type?
mainnet/testnet or also we need to add the network name like `bnb, fantom` etc?

**Comment by boyuan-chen** [comment]
> do you mean the chain name network type?
> mainnet/testnet or also we need to add the network name like `bnb, fantom` etc?

Yes! That will be great!
