### ISSUE TITLE
Gateway Wallet: There is no Alt L1 Bridge available as before.

### ISSUE THREAD

**Issue by GianBobarino** [bobanetwork/boba_legacy#704]
Can you please share more details, what exactly we have to achieve here?

**Comment by sk-enya** [comment]
We have an alt l1 bridge where you can transfer the boba token from Eth L1 to Fantom L1 or <any network L1> to <supported alt l1>


Supported alt bridge we have.

Eth: `fantom, bnb, avax, moonbeam`
fantom: `fantom`
BNB: `bnb`
moonbase: `moonbase`
 


![Image](https://user-images.githubusercontent.com/86316370/232549569-ef265301-4239-4de4-8959-5cd891fcbe4b.png)
![Image](https://user-images.githubusercontent.com/86316370/232549570-34612423-0b15-4007-8d5d-218b124531ca.png)

**Comment by GianBobarino** [comment]
Can we add "Alt-L1 Bridge" rather than just "bridge", thank you
