### ISSUE TITLE
Circle Ci: Update Ci to disable Integrations-test If changes are only for gateway.

### ISSUE THREAD

**Issue by sk-enya** [bobanetwork/boba_legacy#707]
## Issue Type

```
[ x ] bug report
[ ] feature request
```

## Current Behavior

Currently circle ci triggers all the job like integrations-tests even though the changes is only for gateway so better to disable for gateway changes.

## Expected Behavior

Ci should trigger the integration test if we make changes to other files than gateway project.

## Steps to Reproduce

1.
2.
3.

**Comment by sk-enya** [comment]
Instead of changing the existing Circle CI configuration we can easily ask github to skip ci.

If any commit message in your push or the HEAD commit of your PR contains the strings `[skip ci], [ci skip], [no ci], [skip actions], or [actions skip]` workflows triggered on the push or pull_request events will be skipped.

@InoMurko @Boyuan-Chen would love to know your thoughts on this..

**Comment by sk-enya** [comment]
cc @alvaro-ricotta

**Comment by InoMurko** [comment]
Done
