### ISSUE TITLE
When switching to Moonbeam <> Bobabeam chain a banner should appear

### ISSUE THREAD

**Issue by sk-enya** [bobanetwork/boba_legacy#728]
Bobabeam is closing - please withdraw your funds

**Comment by sk-enya** [comment]
Are we also going to remove the support for Moonbeam , Bobabeam in near future?
@InoMurko

**Comment by InoMurko** [comment]
yep!

**Comment by sk-enya** [comment]
![Image](https://user-images.githubusercontent.com/86316370/234141066-449ccf28-5fba-4a4f-8ae6-dd6da545cb3f.png)
![Image](https://user-images.githubusercontent.com/86316370/234141067-8543a098-c1cb-49af-bf01-db30371f33dc.png)
