### ISSUE TITLE
Document Bundler API for docs.boba.network

### ISSUE THREAD

**Issue by wsdt** [bobanetwork/boba_legacy#738]
https://github.com/bobanetwork/boba/pull/698

just some more info - on the same branch ^ - its mostly these two folders
https://github.com/bobanetwork/boba/tree/inomurko/bump-bundler-2/packages/boba/bundler_sdk
https://github.com/bobanetwork/boba/tree/inomurko/bump-bundler-2/packages/boba/bundler
if you look at bundler_sdk's readme - its quite outdated + we need to add docs about the changes we have made to the sdk in order for users to use it
this is the precise upstream commits the latest is synced with
contracts: https://github.com/eth-infinitism/account-abstraction/commit/b18e2333d9f9a0989176382b923457d672d6fcac
bundler: https://github.com/eth-infinitism/bundler/commit/366c7b65af9be8a31f18db939ee05ee298c086cb

reference how docs should look like: https://docs.infura.io/infura/networks/ethereum/json-rpc-methods
sdk: https://pkg.go.dev/crypto/rand#pkg-functions
published on docs.boba.network

**Comment by wsdt** [comment]
https://github.com/bobanetwork/boba/pull/736

**Comment by souradeep-das** [comment]
closed by #736
