### ISSUE TITLE
[docs] Tenderly support in documentation

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#744]
Tenderly is supporting us on two fronts:

- **First one:**

Web3 Gateway (only for Ethereum Boba atm), 
the docs on docs.boba.network need to mention this, similar to Optimism mentioning Alchemy:
<img width="847" alt="image" src="https://user-images.githubusercontent.com/2582555/234839018-fd904ed2-a6ff-42ae-9d0e-475729dff57c.png">

The public endpoints are:
```
We have partnered with Tenderly. 

http://boba-ethereum.gateway.tenderly.co should work 

or alternatively http://gateway.tenderly.co/public/boba-ethereum

These are public and have ip based rate limiting. You can subscribe to Tenderly if you need more
```

- **Second one** is available on ALL chains (excluding Moonbeam since it's shutting down) - Tenderly development platform:

<img width="1376" alt="image" src="https://user-images.githubusercontent.com/2582555/234839779-40ddafb7-46ee-4dec-a2d0-32113874c5a6.png">

These things need to be mentioned, perhaps with some examples...

**Comment by wsdt** [comment]
will do!

**Comment by wsdt** [comment]
Also added to chainlist: 
https://github.com/DefiLlama/chainlist/pull/472

**Comment by InoMurko** [comment]
I think this is done. If not, please reopen.
