### ISSUE TITLE
[AA] fix UserOpMethodHandler estimateUserOperationGas

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#752]
In `UserOpMethodHandler.ts`
```
// todo: validation manager duplicate?
    const errorResult = await this.entryPoint.callStatic
      .simulateValidation(userOp)
      .catch((e) => e)
```
This needs to be routed through `EntryPointWrapper` because of Solidity custom errors.

This currently works (in unit tests) because `UserOpMethodHandler.test.ts` is run against Hardhat. Adapt the tests.

Integration tests don't actually use Bundler RPC method `eth_estimateUserOperationGas` - we should make note in the docs this currently isn't supported.

**Comment by InoMurko** [comment]
@wsdt if you can take over this, @souradeep-das can assist

**Comment by souradeep-das** [comment]
sure, just lmk if this is interesting, otherwise i can take this up too!

**Comment by wsdt** [comment]
@InoMurko @souradeep-das are these issues to be done in bump-bundler-2 or bump-bundler?

**Comment by InoMurko** [comment]
bump-bundler-2 or in develop once it's merged

**Comment by wsdt** [comment]
ok thx!

**Comment by wsdt** [comment]
Added note that estimateUserOperationGas rpc method currently not supported: 
https://github.com/bobanetwork/boba/pull/736/commits/6de81f50110d202caf000144ee08c0efd16c0484
