### ISSUE TITLE
setup dependabot

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#788]
## Issue Type

```
[ ] bug report
[ x] feature request
```

## Current Behavior
We need to asses dependency issues with dependabot.

## Expected Behavior
dependabot should analyze our dependencies and raise PRs to update them

**Comment by InoMurko** [comment]
Additionally: add https://snyk.io/ and https://github.com/m4ll0k/SecretFinder

**Comment by wsdt** [comment]
Github has native support for Dependabot, can try adding the yml file manually (but I don't think they'll execute on that without enabling it in the settings). 

Could you give me (temporary) access to the repo settings? @InoMurko 
Or enable "Dependabot version updates" yourself? 

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#enabling-dependabot-version-updates
