### ISSUE TITLE
Upgrade Teleportation (contract) for variety of tokens and native assets

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#795]
## Issue Type

```
[ ] bug report
[ x] feature request
```

## Current Behavior
Currently Teleportation only works with BOBA as Native asset on (BNB, Avax BOBA) and ERC20 on Ethereum Boba.

## Expected Behavior
We would like the Teleportation to support variety of assets (ERC20 and native assets).

**Freely Teleport BOBA between**: (this should already work)
Ethereum > Ethereum Boba
Ethereum > Avax Boba
Ethereum > BNB Boba

Ethereum Boba > Ethereum
Avax Boba > Ethereum
BNB Boba > Ethereum

Ethereum Boba > Avax Boba
Avax Boba > BNB Boba
BNB Boba > Avax Boba

Ethereum > BNB Boba

**Freely Teleport ETH between**:
Ethereum > Ethereum Boba
Ethereum Boba > Ethereum
(eth doesn't make sense on other chains)

**Freely Teleport USDT between**:
Ethereum > Ethereum Boba 
Ethereum Boba  > Ethereum

**Freely Teleport BNB between**:
Ethereum > Ethereum Boba 
Ethereum Boba  > Ethereum

MVP STATE:
=========
When bridging ETH:
ETH L1 <> BobaETH
BobaAvax > BobaETH
BobaBNB > BobaETH
BobaFantom > BobaETH

When bridging BOBA:
ETH L1 <> All Boba Chains
BobaAvax <> ETH L1 + All Boba Chains
BobaBNB <> ETH L1 + All Boba Chains
BobaFantom <> ETH L1 + All Boba Chains

**Comment by InoMurko** [comment]
<img width="358" alt="image" src="https://github.com/bobanetwork/boba/assets/2582555/ce0c0bf3-b335-48fd-966e-dfa324dc1b39">

**Comment by souradeep-das** [comment]
So we want Teleportation routes even for routes where classic bridging is possible right? to offer a cheaper way to bridge?
(for instance bridging ETH, ETH L1 <> BobaETH)

**Comment by wsdt** [comment]
[ ] Request audit(s) for diff afterwards

**Comment by wsdt** [comment]
@InoMurko @cryptoxman How do we want to handle daily limit, min/max deposit, etc? 
Just handle them separately per asset?
