### ISSUE TITLE
disable Moonbeam integration tests and delete them from repo

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#805]
## Issue Type

```
[ ] bug report
[x ] feature request
```

## Current Behavior
Moonbeam is being shutdown, we won't be rolling out any more updates there.

## Steps to Reproduce

1.
2.
3.

**Comment by InoMurko** [comment]
Please document any other Moonbeam specific implementations that we would need to cleanup!

**Comment by InoMurko** [comment]
Also add Fantom please (remove)

**Comment by souradeep-das** [comment]
Checklist of things that will have to be removed: https://github.com/bobanetwork/boba/issues/820

**Comment by souradeep-das** [comment]
closed by #812
