### ISSUE TITLE
remove all occurances of Rinkeby from the repo

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#809]
```
boba_rinkeby: {
      url: 'https://rinkeby.boba.network',
      bridgeCounterpartUrl: 'https://rinkeby.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161', // public RPC
      accounts: process.env.PRIVATE_KEY !== undefined ? [process.env.PRIVATE_KEY] : [],
    } as any,
```
## Issue Type

```
[x ] bug report
[ ] feature request
```

## Current Behavior
Search for `https://rinkeby.infura.io/v3/`

## Expected Behavior
No more Rinkeby :-)

## Steps to Reproduce

1.
2.
3.

**Comment by InoMurko** [comment]
Also remove `ropsten.infura.io`

**Comment by wsdt** [comment]
Sure thing, any testnet I should add? 
Are we going for Sepolia once we are ready?

**Comment by InoMurko** [comment]
Not for now:
If you see any infura links that should be public, use these:
mainnet.gateway.tenderly.co
goerli.gateway.tenderly.co

L2 Ethereum:
http://gateway.tenderly.co/public/boba-ethereum

**Comment by wsdt** [comment]
Just FYI @InoMurko would replace then all occurrences (config files, code, markdowns etc.) with just mainnet. 
Is that what you want?
