### ISSUE TITLE
Feedback - Rinkeby Fee Switcher & Ecosystem page

### ISSUE THREAD

**Issue by MitchellUnknown** [bobanetwork/boba_legacy#81]
Hey guys, 
I have some feedback for the new rinkeby gateway features. I sincerely apologize for the upcoming MUI inconvenience and potential PTSD.

**Ecosystem page**
(1) Change the color of the ‘non selected’ filter buttons to a more neutral color on the new and improved ecosystem page to make it more visable.

![0 Color Change](https://user-images.githubusercontent.com/90399189/162483645-284e9265-a6e0-4473-b204-d68bc0aedf77.png)

**Fee switcher**
(1) Change the menu picker of the “switch fee” button to a more professional look. At the moment it’s very simple looking, and out of design compared with the rest. This also applies to the DAO menu filter. 

![1 Ecosystem Menu](https://user-images.githubusercontent.com/90399189/162484486-662648f4-571f-42e6-b1fe-cd6e8c589583.png)

![1 Menu Upgrades](https://user-images.githubusercontent.com/90399189/162484777-a0ae8d04-bb50-4775-8b7b-390a17119a61.png)

(2) Give the user a feedback message that they switched the fee token.

![2 Feedback Message Fee Changed](https://user-images.githubusercontent.com/90399189/162484898-09b9d867-5a64-4ae0-8b08-448e586158d5.png)

(3) We need to inform the user more about the new “ fee switcher” with a simple help/ learn more button next to the fee switcher. Because a lot of users will just yolo on buttons and that will cost them money

![3 Learn More Feedback Button](https://user-images.githubusercontent.com/90399189/162485273-3185e61a-6560-4b24-8e68-0f3f8ea103d8.png)

**Fee switcher limitations**
I encountered a couple of scenarios where the user experience could be disturbed. I think in almost all of the scenarios, the best solution could be impossible to implement. Let me explain this further:

(1)
_Metamask account with 0.10 Ether (No Boba funds)
Change fee from Ether > Boba (Successful)_

When the user switch their fee token from Ether > Boba. The user will be unable  to pay for transactions, because he doesn't own any Boba tokens. When he realizes he needs to switch back to Ether as the main fee token. The user is forced to add Boba to his wallet by either bridging it from L1 or sending it from another wallet on L2. Because he has to pay the ‘switch fee’ in Boba, which he can’t. So that's not ideal. 

![S1 Switch Back Loop](https://user-images.githubusercontent.com/90399189/162485850-92ca4cce-7f0b-4494-a70d-6a7f9355b266.png)

_Solution 1:_
Let the user not switch to Boba as a fee token IF his wallet does not contain enough Boba. So block the switch button and let the user know: Not enough funds to cover transactions. Do you want to continue? You have to add more funds. 

_Solution 2:_
Let the user switch back to Ether as a fee token and let him pay for this “switch fee” transaction in Ether IF his boba balance is zero or close to zero. In other words (if it’s even possible) make the “switch fee” transaction payable by EITHER boba/ether. If the user doesn't have enough funds of both in his account, then his last option would be to add funds. 

(2)
_Metamask account with 0.25 Boba (No Ether funds)
Change fee from Boba > Ether (Un-Successful)_

If the user only has boba in his account, he can’t change the fee switcher from Ether > Boba. Therefore the user is forced to add Ether to his account. That really sucks for onboarding new people, especially for the next billion users. Let say people won some boba tokens through twitter giveaways, trivia contests or discord promotions. They have to first bridge ether (can cost more than the prize they won) to access their boba tokens. It would be more user friendly to let them switch the fee token to boba WITH their boba tokens. Now they could use the boba tokens and explore the boba network. They could swap their boba tokens on oolongswap for ether. 

![S2 Possible to Pay with Boba to switch to boba](https://user-images.githubusercontent.com/90399189/162486488-765879a3-5f33-4b08-a35f-6fe26a18e3ce.png)

(3)
_Metamask account with 0.34 Ether and 0.01 Boba
Fee token: BOBA
Change fee from BOBA > Ether (Not possible)_

![S3 Can't switch back](https://user-images.githubusercontent.com/90399189/162488516-62fed9c4-a156-4c2b-982e-06b5f7e847d6.png)

By now we know all the transactions will fail, because there is not enough boba to cover the “switch fee” transaction cost. Even if the user got $900 worth of ETH sitting in his account. The funny thing is, they can't even swap it on oolongswap (eth>boba) because they need to pay that "swap transaction" with boba. This can be fixed if the user can pay the “switch fee” transaction in either Ether or Boba. But if this is not possible because of the limitations of the system. We should make it more clearly to the user that they can't transact when there funds are getting low. 

1 Add a message on the gateway that the user needs to add more funds to cover the cost/switch cost
2 Add this message also on all the other gateway interactions. For example the transfer pop-up menu. Give the user feedback that they need to top up their account. Maybe block or grey out all the interactions/buttons. Because I know for a fact that users will get stuck with the switcher. 

![S3 Switch Back Button](https://user-images.githubusercontent.com/90399189/162488558-2b32ee83-615c-414d-90e0-e79e12b7ddb2.png)

![S3 Switch Ether Back](https://user-images.githubusercontent.com/90399189/162489588-e950abf2-0f7d-434a-87de-248273eb377f.png)

Conclusion:
There are a couple of scenarios where the user will get stuck and forced to bridge more funds to get "unstuck". That will be a super user unfriendly experience. For the time being, if there is no real solution to solve this problem, then we need to inform the user to the max that they can't switch back if they don't have any boba left in their wallet. But in the future, we need to come up with some sort of solution/relayer. Because if we are going to deal with more users, moderators will be flooded with users that are stuck and need some boba to get unstuck. At least, thats my take of it. I could be wrong. 

Anyhow, good job on adding all the good stuff (turing, monsters, hackathon, ecosystem page, fee token and all the other cool stuff) The network is getting better and better each day. <3

**Comment by CAPtheorem** [comment]
thanks @MitchellUnknown this is great feedback as usual. We will tackle the visual glitches (@sk-enya) and separately deal with the `getting-stuck` issue - which is a major one. We have a `MetaTransaction` system in in place where we can charge in the opposite currency to get people unstuck - so you can pay in BOBA to switch from ETH to BOBA if you have zero ETH. We'll try to have that all up by Tuesday.

**Comment by CAPtheorem** [comment]
@sk-enya please tackle the basic visuals. I don't know where @MitchellUnknown is seeing the downgraded picker:
<img width="153" alt="Screen Shot 2022-04-08 at 11 24 56 AM" src="https://user-images.githubusercontent.com/79423264/162500591-a5e3da33-a287-4d02-8b72-395a1b9a982f.png">
As far as I know they should all look like this:
<img width="129" alt="Screen Shot 2022-04-08 at 11 30 34 AM" src="https://user-images.githubusercontent.com/79423264/162500674-d69f6edf-c75f-41c0-b239-4a9feba1e0a9.png">

Please add the (?) tooltip so we can add information for the fee switching

**Comment by MitchellUnknown** [comment]
> thanks @MitchellUnknown this is great feedback as usual. We will tackle the visual glitches (@sk-enya) and separately deal with the `getting-stuck` issue - which is a major one. We have a `MetaTransaction` system in in place where we can charge in the opposite currency to get people unstuck - so you can pay in BOBA to switch from ETH to BOBA if you have zero ETH. We'll try to have that all up by Tuesday.

Awesome! Great job guys. Lot's of work being done. Don't forget to also have time to relax and enjoy the moment!

**Comment by sk-enya** [comment]
Closing as this is outdated.
