### ISSUE TITLE
Show status (block confirmations) for pending deposits

### ISSUE THREAD

**Issue by souradeep-das** [bobanetwork/boba_legacy#819]
## Issue Type

```
[ ] bug report
[x] feature request
```

## Current Behavior
After a deposit to L2, user is not shown a progress bar/meter, while the L2 is waiting for the configured block confirmations to accept the transaction

## Expected Behavior
User is shown the current number of confirmations in the 'status' of their pending deposits. Such that they know when their deposit will be accepted on the L2.

## Suggested Fix
Show the following details on the deposit status
```
{noOfBlocksSinceDepositTx}/ConfirmationBlocksSet
```
{noOfBlocksSinceDepositTx} = the number of ethereum blocks since the deposit transaction
ConfirmationBlocksSet = 64, fixed value

when {noOfBlocksSinceDepositTx} is past ConfirmationBlocksSet, change the status to Finalized

(For reference, the same details/confirmation blocks are shown on most exchanges when funds are deposited)

**Comment by sk-enya** [comment]
As per discussion.

1. show modal on completion of bridging with status like current blocks `blockConfirmYet/64`
2. Once the confirmBlocks are more than 64 the we should close the modal and show message `transactions completed successfully you will have your fund on L2 soon!`

User should be able to close both modal in case if they want to perform any other operation on gateway.

**Comment by sk-enya** [comment]
@souradeep-das just quick question how long does it take to accept the deposit to L2 classic transaction?

https://goerli.etherscan.io/tx/0x38b3516850d521eb06f3879ffc9cd52868ea290432ee2fbe11276e4618be430c
block has not be updated to 64 even after 8min.

![Screenshot 2023-07-26 at 7 23 46 AM](https://github.com/bobanetwork/boba/assets/86316370/4e4c9256-9a7e-4704-9356-5057c6e7ad96)

**Comment by souradeep-das** [comment]
@sk-enya 64 blocks should take approximately 13 mins!
