### ISSUE TITLE
Account abstraction intro docs

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#830]
## Issue Type
https://docs.boba.network/for-developers/account-abstraction

```
[ ] bug report
[x ] feature request
```

## Current Behavior
<img width="693" alt="image" src="https://github.com/bobanetwork/boba/assets/2582555/681a168d-4e32-46b8-87c4-62e5937b60e1">

## Expected Behavior
This section needs a better intro
- into what AA is 
- where it's live (placeholder for bundler urls, contracts)
- make sure to update
https://docs.boba.network/for-developers/network-parameters
https://docs.boba.network/for-developers/network-bnb 

## Steps to Reproduce

1.
2.
3.

**Comment by InoMurko** [comment]
THanks @souradeep-das for pointing out that content has been written: https://github.com/bobanetwork/boba/blob/docs-in-monrepo/boba_documentation/developer/account-abstraction/aa-basics.md
but it doesn't show up on https://docs.boba.network/for-developers/account-abstraction

**Comment by wsdt** [comment]
Seemingly resolved #836

**Comment by wsdt** [comment]
guess this can be closed? 
@souradeep-das @InoMurko

**Comment by souradeep-das** [comment]
yes, think so!
