### ISSUE TITLE
[AA] optimize bundler calls for block ranges

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#866]
## Issue Type

```
[x ] bug report
[ ] feature request
```

## Current Behavior
Currently, the behavior to pull eth_getLogs presumes hardcoded block range of max 5000 blocks. There are providers that currently have a lower value set (Tenderly's limit was 3k) so using that provider would break bundler restart.  

## Expected Behavior
Configurable block range to keep up with the network.

## Steps to Reproduce
Use bundler with block range set less then max `4999` - `5000`.

## Suggested Fix
Configurable via cli.

**Comment by souradeep-das** [comment]
thanks! i'll take this on the same PR

**Comment by InoMurko** [comment]
done
