### ISSUE TITLE
Gateway: Testnet Faucet

### ISSUE THREAD

**Issue by sk-enya** [bobanetwork/boba_legacy#885]
## Issue Type

- [x] bug report

## Current Behavior

Currently we have faucet on gateway for testnet on wallet page. does it make sense to move the faucet on developer docs.

**Comment by sk-enya** [comment]
Discussion with greg!

> _Can faucet be moved to developer docs? The gateway should be primarily user facing, including content for testnet developers is uneccesary_

**Comment by wsdt** [comment]
new faucet for reference: bobanetwork/boba#1020 (only HCaptcha, no Twitter verification anymore)

**Comment by wsdt** [comment]
https://github.com/bobanetwork/gateway/issues/68

**Comment by sk-enya** [comment]
Closing as duplicated with https://github.com/bobanetwork/gateway/issues/68
