### ISSUE TITLE
AA audit request

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#905]
## Issue Type

```
[ ] bug report
[x] feature request
```

## Current Behavior
The current audit of 4337 contracts
https://blog.openzeppelin.com/eip-4337-ethereum-account-abstraction-incremental-audit

## Expected Behavior
What is the diff between the audit from OZ and us (our changes) that we need to audit.

## Steps to Reproduce

1.
2.
3.

**Comment by wsdt** [comment]
Document can be found here (only Enya mails): 
https://docs.google.com/document/d/1u46S01Ew88fl8raFGK3C7AzDfmk3khJb1LUPQvCD8AU/edit?usp=sharing

Feedback welcome

@InoMurko @souradeep-das

**Comment by souradeep-das** [comment]
looks great! thanks!
