### ISSUE TITLE
Graph endpoint for Goerli not live or not documented

### ISSUE THREAD

**Issue by wsdt** [bobanetwork/boba_legacy#910]
## Issue Type

```
[X ] bug report
```

## Current Behavior
Rinkeby graph endpoint document, goerli endpoint with same naming convention not existent. 
![image](https://github.com/bobanetwork/boba/assets/28724551/ec59fa7c-25ea-4b1a-8f28-39046068d9b1)

## Expected Behavior
replacing `rinkeby` with `goerli` works. 

## Steps to Reproduce
Call https://graph.rinkeby.boba.network/subgraphs/name/boba/Bridges/graphql

## Suggested Fix
Document or deploy.

**Comment by wsdt** [comment]
@InoMurko @Boyuan-Chen do we have it deployed? If so, where?

**Comment by boyuan-chen** [comment]
> @InoMurko @Boyuan-Chen do we have it deployed? If so, where?

We don't have the graph node on Goerli L2.

**Comment by wsdt** [comment]
> > @InoMurko @Boyuan-Chen do we have it deployed? If so, where?
> 
> We don't have the graph node on Goerli L2.

is it planned? or shall I remove it from the docs altogether?

**Comment by boyuan-chen** [comment]
I don't think anyone needs it. We can remove it from docs.

**Comment by wsdt** [comment]
Our HybridCompute starter would use it, but it works without too. 
Ok will remove it from the docs then

Thx!
