### ISSUE TITLE
Review upgraded contracts (Audits)

### ISSUE THREAD

**Issue by wsdt** [bobanetwork/boba_legacy#940]
## Issue Type
One of the handover tasks.

## Current Behavior
Audit contracts on testnet deployed: 
https://github.com/bobanetwork/boba/pull/841/files#diff-8d11ed14eb8cf05e01f92a358f954362bfb66f425d7695cd79134f855da5d0f5

## Expected Behavior
Evaluate for proxy collisions, test, etc.

**Comment by wsdt** [comment]
[ ~ ] (Boba) ETH testnet: **waiting for Goerli upgrade, as reset**
[X] (Boba) BNB testnet looks fine
[ ~ ] (Boba) Opera: **see notes below**
[ ~ ]  (Boba) Fuji: **see notes below**
[ ~ ] (Boba) Base: **see notes below**

**Comment by wsdt** [comment]
Opera: 
- L1 looks fine
- L2: 

**need to check if it's just a display error of our block explorer:**
L2LiquidityPool contracts in PR don't seem to exist: 
`0xE7Da2a8EBcbBa0Dc6082B8D0faBAcA0176920760` and `0xB9CeA621C2C9BE002747F2DdB7eB6a7dd0F8F20E`

L1NFTBridge looks fine, while L2NFTBridge also doesn't seem to be deployed on 
`0x30C18d90a6f9B161b8c0BB720b31BcF215FEc12b` and `0xEecAD665ca933eeA4a9a2db600E538c1391930d1

--

TeleporterProxy: 
- New implementation contract deployed, but proxy still points to old one on `0x502310dade5bab1065c788f6b98b78f5fc49fc09`

**Comment by wsdt** [comment]
Fuji: 
- **L1**: Looks fine, some minor remarks:

1.  `L1NFTBridge` implementation not verified

- **L2**: 

1. Teleportation proxy points to `0x502310dade5bab1065c788f6b98b78f5fc49fc09`, which is neither the old (constructor arg) nor the new implementation contract. 

2. New teleportation contract address (that is documented) doesn't seem to be a contract: `0x2001F1B2b72000C34a630a58861E1b5CDe1f63eb`. While the "invalid" address in 1) is - but 7 months old (thus also being a previous version).

**Comment by wsdt** [comment]
Moonbeam: 
- **L1**: LiquidityPool and NFTBridge contracts either deployed on different addresses or blockexplorer display error (need to check)

- **L2**: - same as for L1 -
- TeleportationProxy points to: `0x502310dade5bab1065c788f6b98b78f5fc49fc09` which is 7 months old. On documented implementation address `0x92F4E3796324b916A69c98c96bBd939af19C4AD2` nothing is deployed.

**Comment by wsdt** [comment]
@souradeep-das @InoMurko @Boyuan-Chen 

Had a look at the upgrades, feedback welcome. 

Waiting for Goerli upgrades to be available, so that I can review.

**Comment by boyuan-chen** [comment]
> Fuji:
> 
> * **L1**: Looks fine, some minor remarks:
> 
> 1. `L1NFTBridge` implementation not verified
> 
> * **L2**:
> 
> 1. Teleportation proxy points to `0x502310dade5bab1065c788f6b98b78f5fc49fc09`, which is neither the old (constructor arg) nor the new implementation contract.
> 2. New teleportation contract address (that is documented) doesn't seem to be a contract: `0x2001F1B2b72000C34a630a58861E1b5CDe1f63eb`. While the "invalid" address in 1) is - but 7 months old (thus also being a previous version).

The L1NFTBridge contract is verified.

You might look at the wrong block explorer. The teleportation was updated 22 days ago. 
Proxy: https://blockexplorer.testnet.avax.boba.network/address/0xd68809330075C792C171C450B983F4D18128e9BF/transactions#address-tabs
Implementation:
https://blockexplorer.testnet.avax.boba.network/address/0x2001F1B2b72000C34a630a58861E1b5CDe1f63eb

**Comment by boyuan-chen** [comment]
We don't upgrade contracts for Moonbeam L2 and Fantom L2, because we will shut them down.

**Comment by wsdt** [comment]
> We don't upgrade contracts for Moonbeam L2 and Fantom L2, because we will shut them down.

ok thx! Yeah thought so, was just confused because we still promote it on our website etc.

**Comment by wsdt** [comment]
Just confirmed! Thanks @Boyuan-Chen

**Comment by boyuan-chen** [comment]
Goerli: https://github.com/bobanetwork/boba/pull/941/

**Comment by wsdt** [comment]
Awesome looks good to me! thanks Boyuan!

**Comment by wsdt** [comment]
closing as completed

**Comment by souradeep-das** [comment]
some of these things remain to be done:

i) New (implementation) contracts need to be registered on the AddressManager

ii) DiscretionaryExitFee needs to be redeployed (and UI changes probably, gateway needs to point to this contract instead)

iii) L2NFTBridge (Fuji) contracts needs to be verified

cc @Boyuan-Chen

**Comment by boyuan-chen** [comment]
@souradeep-das https://github.com/bobanetwork/boba/pull/976

**Comment by boyuan-chen** [comment]
@sk-enya Please confirm that the gateway loads the `DiscretionaryExitFee` address from the local json file in the register folder.

**Comment by souradeep-das** [comment]
Thanks @Boyuan-Chen!

**Comment by sk-enya** [comment]
@Boyuan-Chen yes `DiscretionaryExitFee` address is loaded from local json file from register folder.

**Comment by wsdt** [comment]
Closing as last PR has been merged, please feel free to reopen if there seems something missing.
