### ISSUE TITLE
Integration tests seem to be dependent on each other

### ISSUE THREAD

**Issue by wsdt** [bobanetwork/boba_legacy#953]
## Issue Type

```
[x ] bug report
[ ] feature request
```

## Current Behavior
Integration tests within one describe are dependent, which ideally is not the case - but for performance more desireable. 
But some tests accidentally also seem to be dependent on other test **files** which shouldn't be the case and makes it difficult to narrow down certain issues. 

## Expected Behavior
Integration tests within one describe are self-contained and independent. 

## Steps to Reproduce
Referring to https://github.com/bobanetwork/boba/pull/822#issuecomment-1587824414

**Comment by InoMurko** [comment]
we have a very large number of tests. can you be more precise which test are you referring to?

**Comment by wsdt** [comment]
Would have fixed it already if I would know yet, but that's the test that is being influenced by it: 
https://github.com/bobanetwork/boba/pull/822#issuecomment-1587824414

Succeeding when executed isolated, but failing when globally running all integration tests.

**Comment by wsdt** [comment]
with the most recent develop merge the test stopped failing deterministically. 
Seems like that my PR was based on a faulty commit.
