### ISSUE TITLE
How to build rinkeby Boba node, is Boba rinkeby Layer 1 based on Ethereum rinkeky?

### ISSUE THREAD

**Issue by mengyuexxx** [bobanetwork/boba_legacy#99]
I have a problem, I want to build Boba rinkeby node, I deployed it based on docker-compose, but encountered the following error：
![image](https://user-images.githubusercontent.com/97864296/163090675-0163f7f4-2a13-4bea-a3d2-d8404916d0dc.png)

Here is my docker-compose configuration, how do I go about solving it
![image](https://user-images.githubusercontent.com/97864296/163090801-ab0254d0-24c6-4cb1-8e6f-f47f507416e8.png)

**Comment by CAPtheorem** [comment]
Hi! Please open a PR to add this feature - it's super hard to debug a picture of code rather than code. Also, that way, when everything is configured correctly, a boba-rinkeby yaml will be available for the entire community.

**Comment by mengyuexxx** [comment]
This is my docker-compose.yaml config
x-l1_rpc_dtl: &l1_rpc_dtl
  DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT: 'https://eth-rinkeby.alchemyapi.io/v2/kz0KacM3l9zrSYXQmx0rqZN7Hw6DOFUB'

x-l1_rpc_geth: &l1_rpc_geth
  ETH1_HTTP: 'https://eth-rinkeby.alchemyapi.io/v2/kz0KacM3l9zrSYXQmx0rqZN7Hw6DOFUB'

version: "3.9"

services:
  dtl-rinkeby:
    container_name: dtl-rinkeby
    image: bobanetwork/data-transport-layer:release
    env_file:
      -  ../../ops/envs/dtl.env
    environment:
      << : *l1_rpc_dtl
      DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT: https://rinkeby.boba.network
      DATA_TRANSPORT_LAYER__SYNC_FROM_L1: 'false'
      DATA_TRANSPORT_LAYER__SYNC_FROM_L2: 'true'
      DATA_TRANSPORT_LAYER__L2_CHAIN_ID: 28
      DATA_TRANSPORT_LAYER__ETH1_CTC_DEPLOYMENT_HEIGHT: 13502893
      DATA_TRANSPORT_LAYER__POLLING_INTERVAL: 10000
      DATA_TRANSPORT_LAYER__ADDRESS_MANAGER: '0x8376ac6C3f73a25Dd994E0b0669ca7ee0C02F089'
      DATA_TRANSPORT_LAYER__BSS_HARDFORK_1_INDEX: 381145
      DATA_TRANSPORT_LAYER__TURING_V0_HEIGHT: 381145
      DATA_TRANSPORT_LAYER__TURING_V1_HEIGHT: 381145
    volumes:
      - ./:/opt/optimism/packages/data-transport-layer/state-dumps/
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - ${DTL_PORT:-7878}:7878
      - ${REGISTRY_PORT:-8080}:8081

  replica-rinkeby:
    container_name: replica-rinkeby
    depends_on:
      - dtl-rinkeby
    image: bobanetwork/l2geth:release
    deploy:
      replicas: 1
    entrypoint: sh ./geth.sh
    env_file:
      - ../../ops/envs/geth.env
    #volumes:
    #  - ./<YOUR PERSISTED STORAGE>:/root/.ethereum/
    environment:
      << : *l1_rpc_geth
      ROLLUP_TIMESTAMP_REFRESH: 5s
      ROLLUP_STATE_DUMP_PATH: http://dtl-rinkeby:8081/state-dump.latest.json
      ROLLUP_CLIENT_HTTP: http://dtl-rinkeby:7878
      ROLLUP_BACKEND: 'l2'
      ROLLUP_VERIFIER_ENABLE: 'true'
      RETRIES: 60
      # no need to keep this secret, only used internally to sign blocks
      BLOCK_SIGNER_KEY: "6587ae678cf4fc9a33000cdbf9f35226b71dcc6a4684a31203241f9bcfd55d27"
      BLOCK_SIGNER_ADDRESS: "0x00000398232E2064F896018496b4b44b3D62751F"
      ROLLUP_POLL_INTERVAL_FLAG: "10s"
      ROLLUP_ENFORCE_FEES: 'true'
      TURING_CREDIT_ADDRESS: "0xF8D2f1b0292C0Eeef80D8F47661A9DaCDB4b23bf"
      SEQUENCER_CLIENT_HTTP: https://rinkeby.boba.network
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - ${L2GETH_HTTP_PORT:-8549}:8545
      - ${L2GETH_WS_PORT:-8550}:8546`


I run it with these commands

`cd boba/boba_community/boba-node &&
docker-compose up`

how can i fix it, please!

**Comment by mengyuexxx** [comment]
> 
Hi!

This is my docker-compose.yaml config
x-l1_rpc_dtl: &l1_rpc_dtl
DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT: 'https://eth-rinkeby.alchemyapi.io/v2/kz0KacM3l9zrSYXQmx0rqZN7Hw6DOFUB'

x-l1_rpc_geth: &l1_rpc_geth
ETH1_HTTP: 'https://eth-rinkeby.alchemyapi.io/v2/kz0KacM3l9zrSYXQmx0rqZN7Hw6DOFUB'

version: "3.9"

services:
dtl-rinkeby:
container_name: dtl-rinkeby
image: bobanetwork/data-transport-layer:release
env_file:
- ../../ops/envs/dtl.env
environment:
<< : *l1_rpc_dtl
DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT: https://rinkeby.boba.network/
DATA_TRANSPORT_LAYER__SYNC_FROM_L1: 'false'
DATA_TRANSPORT_LAYER__SYNC_FROM_L2: 'true'
DATA_TRANSPORT_LAYER__L2_CHAIN_ID: 28
DATA_TRANSPORT_LAYER__ETH1_CTC_DEPLOYMENT_HEIGHT: 13502893
DATA_TRANSPORT_LAYER__POLLING_INTERVAL: 10000
DATA_TRANSPORT_LAYER__ADDRESS_MANAGER: '0x8376ac6C3f73a25Dd994E0b0669ca7ee0C02F089'
DATA_TRANSPORT_LAYER__BSS_HARDFORK_1_INDEX: 381145
DATA_TRANSPORT_LAYER__TURING_V0_HEIGHT: 381145
DATA_TRANSPORT_LAYER__TURING_V1_HEIGHT: 381145
volumes:
- ./:/opt/optimism/packages/data-transport-layer/state-dumps/
logging:
driver: "json-file"
options:
max-file: "5"
max-size: "10m"
ports:
- ${DTL_PORT:-7878}:7878
- ${REGISTRY_PORT:-8080}:8081

replica-rinkeby:
container_name: replica-rinkeby
depends_on:
- dtl-rinkeby
image: bobanetwork/l2geth:release
deploy:
replicas: 1
entrypoint: sh ./geth.sh
env_file:
- ../../ops/envs/geth.env
#volumes:
# - ./:/root/.ethereum/
environment:
<< : *l1_rpc_geth
ROLLUP_TIMESTAMP_REFRESH: 5s
ROLLUP_STATE_DUMP_PATH: http://dtl-rinkeby:8081/state-dump.latest.json
ROLLUP_CLIENT_HTTP: http://dtl-rinkeby:7878/
ROLLUP_BACKEND: 'l2'
ROLLUP_VERIFIER_ENABLE: 'true'
RETRIES: 60
# no need to keep this secret, only used internally to sign blocks
BLOCK_SIGNER_KEY: "6587ae678cf4fc9a33000cdbf9f35226b71dcc6a4684a31203241f9bcfd55d27"
BLOCK_SIGNER_ADDRESS: "0x00000398232E2064F896018496b4b44b3D62751F"
ROLLUP_POLL_INTERVAL_FLAG: "10s"
ROLLUP_ENFORCE_FEES: 'true'
TURING_CREDIT_ADDRESS: "0xF8D2f1b0292C0Eeef80D8F47661A9DaCDB4b23bf"
SEQUENCER_CLIENT_HTTP: https://rinkeby.boba.network/
logging:
driver: "json-file"
options:
max-file: "5"
max-size: "10m"
ports:
- ${L2GETH_HTTP_PORT:-8549}:8545
- ${L2GETH_WS_PORT:-8550}:8546`

I run it with these commands

cd boba/boba_community/boba-node && docker-compose up

how can i fix it, please!

**Comment by mengyuexxx** [comment]
> Hi! Please open a PR to add this feature - it's super hard to debug a picture of code rather than code. Also, that way, when everything is configured correctly, a boba-rinkeby yaml will be available for the entire community.


Hi!
This is my docker-compose.yaml config
x-l1_rpc_dtl: &l1_rpc_dtl
DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT: 'https://eth-rinkeby.alchemyapi.io/v2/kz0KacM3l9zrSYXQmx0rqZN7Hw6DOFUB'

x-l1_rpc_geth: &l1_rpc_geth
ETH1_HTTP: 'https://eth-rinkeby.alchemyapi.io/v2/kz0KacM3l9zrSYXQmx0rqZN7Hw6DOFUB'

version: "3.9"

services:
dtl-rinkeby:
container_name: dtl-rinkeby
image: bobanetwork/data-transport-layer:release
env_file:
- ../../ops/envs/dtl.env
environment:
<< : *l1_rpc_dtl
DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT: https://rinkeby.boba.network/
DATA_TRANSPORT_LAYER__SYNC_FROM_L1: 'false'
DATA_TRANSPORT_LAYER__SYNC_FROM_L2: 'true'
DATA_TRANSPORT_LAYER__L2_CHAIN_ID: 28
DATA_TRANSPORT_LAYER__ETH1_CTC_DEPLOYMENT_HEIGHT: 13502893
DATA_TRANSPORT_LAYER__POLLING_INTERVAL: 10000
DATA_TRANSPORT_LAYER__ADDRESS_MANAGER: '0x8376ac6C3f73a25Dd994E0b0669ca7ee0C02F089'
DATA_TRANSPORT_LAYER__BSS_HARDFORK_1_INDEX: 381145
DATA_TRANSPORT_LAYER__TURING_V0_HEIGHT: 381145
DATA_TRANSPORT_LAYER__TURING_V1_HEIGHT: 381145
volumes:
- ./:/opt/optimism/packages/data-transport-layer/state-dumps/
logging:
driver: "json-file"
options:
max-file: "5"
max-size: "10m"
ports:
- ${DTL_PORT:-7878}:7878
- ${REGISTRY_PORT:-8080}:8081

replica-rinkeby:
container_name: replica-rinkeby
depends_on:
- dtl-rinkeby
image: bobanetwork/l2geth:release
deploy:
replicas: 1
entrypoint: sh ./geth.sh
env_file:
- ../../ops/envs/geth.env
#volumes:
# - ./:/root/.ethereum/
environment:
<< : *l1_rpc_geth
ROLLUP_TIMESTAMP_REFRESH: 5s
ROLLUP_STATE_DUMP_PATH: http://dtl-rinkeby:8081/state-dump.latest.json
ROLLUP_CLIENT_HTTP: http://dtl-rinkeby:7878/
ROLLUP_BACKEND: 'l2'
ROLLUP_VERIFIER_ENABLE: 'true'
RETRIES: 60
# no need to keep this secret, only used internally to sign blocks
BLOCK_SIGNER_KEY: "6587ae678cf4fc9a33000cdbf9f35226b71dcc6a4684a31203241f9bcfd55d27"
BLOCK_SIGNER_ADDRESS: "0x00000398232E2064F896018496b4b44b3D62751F"
ROLLUP_POLL_INTERVAL_FLAG: "10s"
ROLLUP_ENFORCE_FEES: 'true'
TURING_CREDIT_ADDRESS: "0xF8D2f1b0292C0Eeef80D8F47661A9DaCDB4b23bf"
SEQUENCER_CLIENT_HTTP: https://rinkeby.boba.network/
logging:
driver: "json-file"
options:
max-file: "5"
max-size: "10m"
ports:
- ${L2GETH_HTTP_PORT:-8549}:8545
- ${L2GETH_WS_PORT:-8550}:8546

I run it with these commands

cd boba/boba_community/boba-node && docker-compose up

how can i fix it, please!

**Comment by mengyuexxx** [comment]
Hi! This is my docker-compose.yaml 
`x-l1_rpc_dtl: &l1_rpc_dtl
  DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT: 'https://eth-rinkeby.alchemyapi.io/v2/kz0KacM3l9zrSYXQmx0rqZN7Hw6DOFUB'

x-l1_rpc_geth: &l1_rpc_geth
  ETH1_HTTP: 'https://eth-rinkeby.alchemyapi.io/v2/kz0KacM3l9zrSYXQmx0rqZN7Hw6DOFUB'

version: "3.9"

services:
  dtl-rinkeby:
    container_name: dtl-rinkeby
    image: bobanetwork/data-transport-layer:release
    env_file:
      -  ../../ops/envs/dtl.env
    environment:
      << : *l1_rpc_dtl
      DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT: https://rinkeby.boba.network
      DATA_TRANSPORT_LAYER__SYNC_FROM_L1: 'false'
      DATA_TRANSPORT_LAYER__SYNC_FROM_L2: 'true'
      DATA_TRANSPORT_LAYER__L2_CHAIN_ID: 28
      DATA_TRANSPORT_LAYER__ETH1_CTC_DEPLOYMENT_HEIGHT: 13502893
      DATA_TRANSPORT_LAYER__POLLING_INTERVAL: 10000
      DATA_TRANSPORT_LAYER__ADDRESS_MANAGER: '0x93A96D6A5beb1F661cf052722A1424CDDA3e9418'
      DATA_TRANSPORT_LAYER__BSS_HARDFORK_1_INDEX: 381145
      DATA_TRANSPORT_LAYER__TURING_V0_HEIGHT: 381145
      DATA_TRANSPORT_LAYER__TURING_V1_HEIGHT: 381145
    volumes:
      - ./:/opt/optimism/packages/data-transport-layer/state-dumps/
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - ${DTL_PORT:-7878}:7878
      - ${REGISTRY_PORT:-8080}:8081

  replica-rinkeby:
    container_name: replica-rinkeby
    depends_on:
      - dtl-rinkeby
    image: bobanetwork/l2geth:release
    deploy:
      replicas: 1
    entrypoint: sh ./geth.sh
    env_file:
      - ../../ops/envs/geth.env
    #volumes:
    #  - ./<YOUR PERSISTED STORAGE>:/root/.ethereum/
    environment:
      << : *l1_rpc_geth
      ROLLUP_TIMESTAMP_REFRESH: 5s
      ROLLUP_STATE_DUMP_PATH: http://dtl-rinkeby:8081/state-dump.latest.json
      ROLLUP_CLIENT_HTTP: http://dtl-rinkeby:7878
      ROLLUP_BACKEND: 'l2'
      ROLLUP_VERIFIER_ENABLE: 'true'
      RETRIES: 60
      # no need to keep this secret, only used internally to sign blocks
      BLOCK_SIGNER_KEY: "f705c8b61d1f89041224ad5a428cd37718dcd3cfb2200ee4f80630528bd3b178"
      BLOCK_SIGNER_ADDRESS: "0x4CE45e9911Db21db1A85b0F03659dE68d015C62e"
      ROLLUP_POLL_INTERVAL_FLAG: "10s"
      ROLLUP_ENFORCE_FEES: 'true'
      TURING_CREDIT_ADDRESS: "0xF8D2f1b0292C0Eeef80D8F47661A9DaCDB4b23bf"
      SEQUENCER_CLIENT_HTTP: https://rinkeby.boba.network
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - ${L2GETH_HTTP_PORT:-8549}:8545
      - ${L2GETH_WS_PORT:-8550}:8546`

I run it with this command:
`cd boba/boba_community/boba-node && docker-compose up`


**and I get this error**:


replica-rinkeby    | TRACE[04-13|08:37:30.902] Waiting for transaction to be added to chain hash=0x4da7aadbf1deb70371c016f3d808a84caf6a92ea98d99b7b5830759fd2a3be6d
replica-rinkeby    | DEBUG[04-13|08:37:30.902] Attempting to commit rollup transaction  hash=0x4da7aadbf1deb70371c016f3d808a84caf6a92ea98d99b7b5830759fd2a3be6d
replica-rinkeby    | TRACE[04-13|08:37:30.909] Skipping account with high nonce         sender=0x498968C2B945Ac37b78414f66167b0786E522636 nonce=44142
replica-rinkeby    | ERROR[04-13|08:37:30.910] Problem committing transaction           msg="Cannot commit transaction in miner"
replica-rinkeby    | ERROR[04-13|08:37:30.910] Got error waiting for transaction to be added to chain msg="Cannot commit transaction in miner"
replica-rinkeby    | ERROR[04-13|08:37:30.910] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: Cannot commit transaction in miner"
dtl-rinkeby        | {"level":30,"time":1649839059616,"method":"GET","url":"/transaction/latest?backend=l2","elapsed":1150,"msg":"Served HTTP Request"}
replica-rinkeby    | INFO [04-13|08:37:39.632] Syncing transaction range                start=1 end=40000 backend=l2
dtl-rinkeby        | {"level":30,"time":1649839059943,"method":"GET","url":"/transaction/index/1?backend=l2","elapsed":12,"msg":"Served HTTP Request"}
replica-rinkeby    | TRACE[04-13|08:37:39.948] Applying indexed transaction             index=1
replica-rinkeby    | DEBUG[04-13|08:37:39.949] Applying transaction to tip              index=1     hash=0xad447af1b0636421254fdbf488f73bf20cc45e8548cb171d7f3cbc024ae9ad5e origin=sequencer
replica-rinkeby    | TRACE[04-13|08:37:39.949] Waiting for transaction to be added to chain hash=0xad447af1b0636421254fdbf488f73bf20cc45e8548cb171d7f3cbc024ae9ad5e
replica-rinkeby    | DEBUG[04-13|08:37:39.950] Attempting to commit rollup transaction  hash=0xad447af1b0636421254fdbf488f73bf20cc45e8548cb171d7f3cbc024ae9ad5e
replica-rinkeby    | TRACE[04-13|08:37:39.952] Skipping account with high nonce         sender=0x8d86Bc475bEDCB08179c5e6a4d494EbD3b44Ea8B nonce=28980
replica-rinkeby    | ERROR[04-13|08:37:39.952] Problem committing transaction           msg="Cannot commit transaction in miner"
replica-rinkeby    | ERROR[04-13|08:37:39.952] Got error waiting for transaction to be added to chain msg="Cannot commit transaction in miner"
replica-rinkeby    | ERROR[04-13|08:37:39.953] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: Cannot commit transaction in miner"
dtl-rinkeby        | {"level":30,"time":1649839064785,"fromBlock":41001,"toBlock":42001,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Optimism)"}
dtl-rinkeby        | {"level":30,"time":1649839069109,"method":"GET","url":"/transaction/latest?backend=l2","elapsed":1268,"msg":"Served HTTP Request"}
replica-rinkeby    | INFO [04-13|08:37:49.114] Syncing transaction range                start=1 end=41000 backend=l2


How can I fix it? please

**Comment by nebojsa-ristovic** [comment]
@mengyuexxx what was the cause of this error and how you resolved it?
