### ISSUE TITLE
Faucet redesign

### ISSUE THREAD

**Issue by wsdt** [bobanetwork/boba_legacy#996]
## Issue Type

```
[ ] bug report
[ x] feature request
```

## Current Behavior
Twitter API faucets don't work without premium anymore. Switched to local file system based verification temporarily. 
Consider proper redesign, captcha, other social media verification etc. 

Related to #995 #989

**Comment by InoMurko** [comment]
FYI: the faucet redesigned will be used on **mainnets** as well. Do they need a new design? @thenursegreg42069

**Comment by alvaro-ricotta** [comment]
FYI: we can use discord instead, only for verified accounts with mobile phone + email

**Comment by InoMurko** [comment]
That sounds too intrusive. I wouldn’t give my phone number

**Comment by alvaro-ricotta** [comment]
You should not request anything, just allow access to the service for individuals with KYC. This way, we prevent alt accounts from draining our faucet.

**Comment by wsdt** [comment]
We could check if Discord member yes/no then x tokens per 24h.

**Comment by InoMurko** [comment]
https://gnosisfaucet.com/ this looks simple and OK to me

**Comment by thenursegreg42069** [comment]
yes we would like to have myself and curtis review the user facing design once it is complete and before any public release

I've seen discord faucets work just fine in the past if you allow only verified accounts

**Comment by alvaro-ricotta** [comment]
@InoMurko https://github.com/Hammad69275/NoCaptchaSolver

**Comment by wsdt** [comment]
if we go for a non HybridCompute approach anyway, we could also consider the PoWFaucet (guess one of the dev-friendliest)

**Comment by wsdt** [comment]
> https://gnosisfaucet.com/ this looks simple and OK to me

starting with HCaptcha as suggested by Ino. 
Please let me know if you prefer an alternative.

**Comment by wsdt** [comment]
closing as completed, opening a Frontend issue
